/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: amogusstrikesback2 (https://sketchfab.com/amogusstrikesback2)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sports-car-racing-paris-1a2b3ec183c44870896c3e2d9aa6e146
Title: sports car racing paris
*/

import { useGLTF } from "@react-three/drei";
import ArcofTriumph from "/ParisScene/ArcdeTriumphe.glb";

export default function AdT(props) {
  const { nodes, materials } = useGLTF(ArcofTriumph);
  return (
    <group {...props} dispose={null} ref={props.innerRef}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.kalusuo_1_D_kalusuo_1_0.geometry}
        material={materials["D_kalusuo_1.002"]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  );
}
