/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Divine Horizon Studios (https://sketchfab.com/DivineHorizonStudios)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/white-birch-28b0ff35099042c484b13a9ce939912f
Title: White Birch
*/

import { useGLTF } from '@react-three/drei'
import birch from "/ParisScene/white_birch.glb"

export default function Birch3(props) {
  const { nodes, materials } = useGLTF(birch)
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2.geometry}
          material={materials.Material_Mat}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_3.geometry}
          material={materials.White_Mat}
        />
      </group>
    </group>
  )
}
