/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: evolveduk (https://sketchfab.com/evolveduk)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/birch-tree-aa842dffd9654d33b8b91170ce83c172
Title: Birch tree
*/

import { useGLTF } from '@react-three/drei'
import birch_1 from "/ParisScene/birch_tree.glb"

export default function Birch1(props) {
  const { nodes, materials } = useGLTF(birch_1)
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.bark11_0_bark11_0Mat_0.geometry}
          material={materials.bark11_0Mat}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.birch_leaf_1_birch_leaf_1Mat_0.geometry}
          material={materials.birch_leaf_1Mat}
        />
      </group>
    </group>
  )
}
