/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Milisandra (https://sketchfab.com/Milisandra)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/tree-5396ddc23e2a42cd88d7640557def9a2
Title: Tree
*/

import { useGLTF } from '@react-three/drei'
import tree from "/ParisScene/tree.glb"

export default function Birch2(props) {
  const { nodes, materials } = useGLTF(tree)
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['tree_����������������001_0'].geometry}
            material={materials['.001']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['tree_����������������001_0_1'].geometry}
            material={materials['.001']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['leaves_����������������_0'].geometry}
            material={materials.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['leaves_����������������_0_1'].geometry}
            material={materials.material}
          />
        </group>
      </group>
    </group>
  )
}

