/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: amogusstrikesback2 (https://sketchfab.com/amogusstrikesback2)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/drift-clash-uluru-aa618de0d366497f89f8ee8fa9dd392c
Title: drift clash uluru
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import scene from '/drift_clash_uluru.glb';

export default function DriftClashUluru(props) {
  const { nodes, materials } = useGLTF(scene)
  return (
    <group {...props} dispose={null} scale={50}>
      <group scale={0.01}>
        <group position={[-139.441, -8.99, 37.744]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Character_Pose_01_SR_Character_Texture_Rider_Blue_0.geometry}
            material={materials.SR_Character_Texture_Rider_Blue}
            position={[266.86, 12.41, -43.6]}
            rotation={[0, -0.808, 0]}
            scale={0.5}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Character_Pose_03_SR_Character_Texture_Rider_Blue_0.geometry}
            material={materials.SR_Character_Texture_Rider_Blue}
            position={[260.121, 12.558, -55.215]}
            rotation={[0, -0.974, 0]}
            scale={0.5}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Character_Pose_02_SR_Character_Texture_Rider_Blue_0.geometry}
            material={materials.SR_Character_Texture_Rider_Blue}
            position={[256.716, 12.626, -58.419]}
            rotation={[0, -0.04, 0.014]}
            scale={0.5}
          />
        </group>
        <group position={[0, 5.3, 0]}>
          <group position={[138.68, 1.13, 177.25]} rotation={[Math.PI, 0.426, Math.PI]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Base001_MiscTrack_0.geometry}
              material={materials.MiscTrack}
              position={[0, 0.184, -0.136]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Wings_MiscTrack_0.geometry}
              material={materials.MiscTrack}
              position={[0, 13.691, 0.887]}
              scale={1.362}
            />
          </group>
          <group position={[167.4, -2.95, 168]} rotation={[Math.PI, 0.426, Math.PI]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Base002_MiscTrack_0.geometry}
              material={materials.MiscTrack}
              position={[0, 0.184, -0.136]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Wings001_MiscTrack_0.geometry}
              material={materials.MiscTrack}
              position={[0, 13.691, 0.887]}
              scale={1.362}
            />
          </group>
          <group position={[176.33, -3.81, 121.62]} rotation={[Math.PI, 0.426, Math.PI]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Base003_MiscTrack_0.geometry}
              material={materials.MiscTrack}
              position={[0, 0.184, -0.136]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Wings002_MiscTrack_0.geometry}
              material={materials.MiscTrack}
              position={[0, 13.691, 0.887]}
              scale={1.362}
            />
          </group>
          <group position={[209.26, -1.26, 148.43]} rotation={[Math.PI, 0.426, Math.PI]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Base004_MiscTrack_0.geometry}
              material={materials.MiscTrack}
              position={[0, 0.184, -0.136]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Wings003_MiscTrack_0.geometry}
              material={materials.MiscTrack}
              position={[0, 13.691, 0.887]}
              scale={1.362}
            />
          </group>
          <group position={[198.6, -4.34, 241.7]} rotation={[Math.PI, 0.426, Math.PI]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Base005_MiscTrack_0.geometry}
              material={materials.MiscTrack}
              position={[0, 0.184, -0.136]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Wings004_MiscTrack_0.geometry}
              material={materials.MiscTrack}
              position={[0, 13.691, 0.887]}
              scale={1.362}
            />
          </group>
          <group position={[127.2, 2.57, 161.6]} rotation={[Math.PI, 0.426, Math.PI]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Base006_MiscTrack_0.geometry}
              material={materials.MiscTrack}
              position={[0, 0.184, -0.136]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Wings005_MiscTrack_0.geometry}
              material={materials.MiscTrack}
              position={[0, 13.691, 0.887]}
              scale={1.362}
            />
          </group>
          <group position={[234.7, -4.9, 140.3]} rotation={[Math.PI, 0.426, Math.PI]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Base007_MiscTrack_0.geometry}
              material={materials.MiscTrack}
              position={[0, 0.184, -0.136]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Wings006_MiscTrack_0.geometry}
              material={materials.MiscTrack}
              position={[0, 13.691, 0.887]}
              scale={1.362}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.bannerbig01_SPW_Urban_Road_Props_03_0.geometry}
            material={materials.SPW_Urban_Road_Props_03}
            position={[67.643, -3.563, 65.404]}
            rotation={[-Math.PI / 2, 0, 0.311]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['bannerbig01_(1)_SPW_Urban_Road_Props_03_0'].geometry}
            material={materials.SPW_Urban_Road_Props_03}
            position={[2.45, -3.45, -81.66]}
            rotation={[-Math.PI / 2, 0, -0.323]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SPW_Urban_Props_Dumpster_01__1__SPW_Urban_Props_0.geometry}
            material={materials.SPW_Urban_Props}
            position={[209.71, 8.273, -145.21]}
            rotation={[-Math.PI / 2, 0, 0.945]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SPW_Urban_Props_Dumpster_01__2__SPW_Urban_Props_0.geometry}
            material={materials.SPW_Urban_Props}
            position={[209.71, 8.26, -145.21]}
            rotation={[-Math.PI / 2, 0, 0.945]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SPW_Urban_Props_Dumpster_01__3__SPW_Urban_Props_0.geometry}
            material={materials.SPW_Urban_Props}
            position={[209.71, 8.26, -145.21]}
            rotation={[-Math.PI / 2, 0, 0.945]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SPW_Urban_Props_Roof_Antenna_SPW_Urban_Props_0.geometry}
            material={materials.SPW_Urban_Props}
            position={[414.9, 19.9, -175.3]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SPW_Urban_Road_Props_Billboard_02_SPW_Urban_Road_Props_03_0.geometry}
            material={materials.SPW_Urban_Road_Props_03}
            position={[27.6, 12.43, -71.08]}
            rotation={[-Math.PI / 2, -0.031, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SR_Prop_Camera_SimpleTown001_0.geometry}
            material={materials['SimpleTown.001']}
            position={[293.26, 3.76, -14.57]}
            rotation={[-Math.PI / 2, 0, -2.672]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['SR_Prop_Camera_(1)_SimpleTown001_0'].geometry}
            material={materials['SimpleTown.001']}
            position={[195.22, 3.76, 243.73]}
            rotation={[-Math.PI / 2, 0, 1.791]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SR_Prop_Flag_01_SimpleTown001_0.geometry}
            material={materials['SimpleTown.001']}
            position={[111.95, 8.95, -157.22]}
            rotation={[-1.577, -0.011, 1.171]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SR_Prop_StadiumLights_SimpleTown001_0.geometry}
            material={materials['SimpleTown.001']}
            position={[-118.28, 7.14, -190.57]}
            rotation={[-Math.PI / 2, 0, -0.826]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SR_Prop_StadiumLights__1__SimpleTown001_0.geometry}
            material={materials['SimpleTown.001']}
            position={[21.82, 5.14, -32.6]}
            rotation={[-Math.PI / 2, 0, -0.798]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SR_Prop_StadiumLights__2__SimpleTown001_0.geometry}
            material={materials['SimpleTown.001']}
            position={[113.887, 6.63, 240.225]}
            rotation={[-Math.PI / 2, 0, 1.353]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SR_Prop_StadiumLights__4__SimpleTown001_0.geometry}
            material={materials['SimpleTown.001']}
            position={[126.93, 2.86, -44.37]}
            rotation={[-1.565, 0.056, -0.098]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['SR_Prop_StadiumLights_(1)_SimpleTown001_0'].geometry}
            material={materials['SimpleTown.001']}
            position={[-42.31, 7.57, 76.42]}
            rotation={[-Math.PI / 2, 0, 1.181]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes['SPW_Urban_Road_Props_Billboard_02_(1)_SPW_Urban_Road_Props_03_0'].geometry
            }
            material={materials.SPW_Urban_Road_Props_03}
            position={[41.02, 7.92, 203.55]}
            rotation={[-1.551, -0.03, -1.497]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['bannerbig01_(2)_SPW_Urban_Road_Props_03_0'].geometry}
            material={materials.SPW_Urban_Road_Props_03}
            position={[-103.65, 4.03, 4.64]}
            rotation={[-1.596, -0.015, -1.018]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SR_Prop_SmashedCar_01_SimpleTown001_0.geometry}
            material={materials['SimpleTown.001']}
            position={[-147.13, -4.92, -59.53]}
            rotation={[0, 0, 0.019]}
            scale={0.8}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SR_Prop_Barrier_Concrete_02_SimpleTown001_0.geometry}
            material={materials['SimpleTown.001']}
            position={[-127.21, -3.86, -51.63]}
            rotation={[0.129, -0.439, 0.017]}
            scale={0.5}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SR_Prop_Barrier_Plastic_02_SimpleTown001_0.geometry}
            material={materials['SimpleTown.001']}
            position={[-83.22, -1.67, 71.71]}
            rotation={[0, 0, 0.074]}
            scale={0.5}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['SR_Prop_Barrier_Plastic_02_(1)_SimpleTown001_0'].geometry}
            material={materials['SimpleTown.001']}
            position={[-81.47, -1.57, 71.71]}
            rotation={[0, 0, 0.074]}
            scale={0.5}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['SR_Prop_Barrier_Plastic_02_(2)_SimpleTown001_0'].geometry}
            material={materials['SimpleTown.001']}
            position={[-88.84, -2.31, 98.05]}
            rotation={[0, -0.528, 0.074]}
            scale={0.5}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['SR_Prop_Barrier_Plastic_02_(3)_SimpleTown001_0'].geometry}
            material={materials['SimpleTown.001']}
            position={[-90.29, -2.41, 97.17]}
            rotation={[0, -0.528, 0.074]}
            scale={0.5}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.advground_SPW_Urban_Road_Props_03_0.geometry}
            material={materials.SPW_Urban_Road_Props_03}
            position={[48.46, -2.617, 38.617]}
            rotation={[-1.57, 0.012, 0.234]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['SR_Prop_Barrier_Concrete_02_(1)_SimpleTown001_0'].geometry}
            material={materials['SimpleTown.001']}
            position={[97.57, -1.46, -32.79]}
            rotation={[-0.005, 0.749, 0.052]}
            scale={0.5}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['SR_Prop_Barrier_Plastic_02_(4)_SimpleTown001_0'].geometry}
            material={materials['SimpleTown.001']}
            position={[-28.55, -3.36, -21.47]}
            rotation={[0, -0.473, 0.039]}
            scale={0.5}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['SR_Prop_Barrier_Plastic_02_(5)_SimpleTown001_0'].geometry}
            material={materials['SimpleTown.001']}
            position={[-27.02, -3.37, -20.69]}
            rotation={[0, -0.473, 0.005]}
            scale={0.5}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.sunnyGarageBanner_SunnySideGarage_0.geometry}
            material={materials.SunnySideGarage}
            position={[91.8, -3.42, 9.72]}
            rotation={[-Math.PI / 2, 0, 2.393]}
          />
        </group>
        <group position={[-155.061, -3.882, 50.592]}>
          <group position={[-17.57, 4.86, 10.17]} rotation={[0, 1.545, 0]} scale={[0.5, 0.5, 0.6]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.SR_Veh_StreetCar_Black_SimpleTown004_0.geometry}
              material={materials['SimpleTown.004']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.SR_Veh_Wheel_FL_SimpleTown004_0.geometry}
              material={materials['SimpleTown.004']}
              position={[1.128, 0.609, 1.839]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.SR_Veh_Wheel_FR_SimpleTown004_0.geometry}
              material={materials['SimpleTown.004']}
              position={[-1.128, 0.609, 1.839]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.SR_Veh_Wheel_RL_SimpleTown004_0.geometry}
              material={materials['SimpleTown.004']}
              position={[1.128, 0.609, -1.799]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.SR_Veh_Wheel_RR_SimpleTown004_0.geometry}
              material={materials['SimpleTown.004']}
              position={[-1.128, 0.609, -1.799]}
            />
          </group>
          <group position={[-15.69, 4.88, 6.17]} rotation={[0.022, 1.188, -0.016]} scale={0.5}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.SR_Veh_StockCar_Green_SimpleTown004_0.geometry}
              material={materials['SimpleTown.004']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.SR_Veh_StockCar_Wheel_FL_SimpleTown004_0.geometry}
              material={materials['SimpleTown.004']}
              position={[1.151, 0.564, 2.213]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.SR_Veh_StockCar_Wheel_FR_SimpleTown004_0.geometry}
              material={materials['SimpleTown.004']}
              position={[-1.151, 0.564, 2.213]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.SR_Veh_StockCar_Wheel_RL_SimpleTown004_0.geometry}
              material={materials['SimpleTown.004']}
              position={[1.151, 0.564, -2.102]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.SR_Veh_StockCar_Wheel_RR_SimpleTown004_0.geometry}
              material={materials['SimpleTown.004']}
              position={[-1.151, 0.564, -2.102]}
            />
          </group>
          <group position={[35.377, 5.795, -30.504]} rotation={[0.377, -1.092, 0.324]} scale={0.5}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.SR_Veh_OffRoadTruck_Yellow_SimpleTown004_0.geometry}
              material={materials['SimpleTown.004']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.SR_Veh_OffRoadTruck_Wheel_FL_SimpleTown004_0.geometry}
              material={materials['SimpleTown.004']}
              position={[1.245, 0.921, 2.744]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.SR_Veh_OffRoadTruck_Wheel_FR_SimpleTown004_0.geometry}
              material={materials['SimpleTown.004']}
              position={[-1.247, 0.921, 2.744]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.SR_Veh_OffRoadTruck_Wheel_RL_SimpleTown004_0.geometry}
              material={materials['SimpleTown.004']}
              position={[1.245, 0.921, -2.581]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.SR_Veh_OffRoadTruck_Wheel_RR_SimpleTown004_0.geometry}
              material={materials['SimpleTown.004']}
              position={[-1.246, 0.921, -2.581]}
            />
          </group>
          <group position={[-14.27, 4.811, 3.95]} rotation={[0, 1.253, 0]} scale={0.5}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.SR_Veh_MuscleSports_Purple_SimpleTown004_0.geometry}
              material={materials['SimpleTown.004']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.SR_Veh_MuscleSports_Wheel_FL_SimpleTown004_0.geometry}
              material={materials['SimpleTown.004']}
              position={[1.406, 0.75, 2.482]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.SR_Veh_MuscleSports_Wheel_FR_SimpleTown004_0.geometry}
              material={materials['SimpleTown.004']}
              position={[-1.406, 0.75, 2.482]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.SR_Veh_MuscleSports_Wheel_RL_SimpleTown004_0.geometry}
              material={materials['SimpleTown.004']}
              position={[1.406, 0.75, -2.076]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.SR_Veh_MuscleSports_Wheel_RR_SimpleTown004_0.geometry}
              material={materials['SimpleTown.004']}
              position={[-1.406, 0.75, -2.076]}
            />
          </group>
          <group position={[-9.33, 4.89, -5.59]} rotation={[Math.PI, 1.517, Math.PI]} scale={0.5}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.SR_Veh_MuscleCar_Red_SimpleTown004_0.geometry}
              material={materials['SimpleTown.004']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.SR_Veh_MuscleCar_Wheel_FL_SimpleTown004_0.geometry}
              material={materials['SimpleTown.004']}
              position={[1.134, 0.617, 2.521]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.SR_Veh_MuscleCar_Wheel_FR_SimpleTown004_0.geometry}
              material={materials['SimpleTown.004']}
              position={[-1.134, 0.617, 2.521]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.SR_Veh_MuscleCar_Wheel_RL_SimpleTown004_0.geometry}
              material={materials['SimpleTown.004']}
              position={[1.134, 0.617, -2.181]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.SR_Veh_MuscleCar_Wheel_RR_SimpleTown004_0.geometry}
              material={materials['SimpleTown.004']}
              position={[-1.134, 0.617, -2.181]}
            />
          </group>
          <group position={[-7.41, 4.95, -10.09]} rotation={[0, 1.354, 0]} scale={0.5}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.SR_Veh_DerbyCar_Orange_SimpleTown004_0.geometry}
              material={materials['SimpleTown.004']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.SR_Veh_DerbyCar_Wheel_FL_SimpleTown004_0.geometry}
              material={materials['SimpleTown.004']}
              position={[1.133, 0.555, 1.933]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.SR_Veh_DerbyCar_Wheel_FR_SimpleTown004_0.geometry}
              material={materials['SimpleTown.004']}
              position={[-1.133, 0.555, 1.933]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.SR_Veh_DerbyCar_Wheel_RL_SimpleTown004_0.geometry}
              material={materials['SimpleTown.004']}
              position={[1.133, 0.555, -2.315]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.SR_Veh_DerbyCar_Wheel_RR_SimpleTown004_0.geometry}
              material={materials['SimpleTown.004']}
              position={[-1.133, 0.555, -2.315]}
            />
          </group>
          <group position={[274.43, 7.49, -71.04]} rotation={[0, -0.371, 0]} scale={0.5}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['SR_Veh_MuscleCar_Red_(1)_SimpleTown004_0'].geometry}
              material={materials['SimpleTown.004']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.SR_Veh_MuscleCar_Wheel_FL001_SimpleTown004_0.geometry}
              material={materials['SimpleTown.004']}
              position={[1.134, 0.617, 2.521]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.SR_Veh_MuscleCar_Wheel_FR001_SimpleTown004_0.geometry}
              material={materials['SimpleTown.004']}
              position={[-1.134, 0.617, 2.521]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.SR_Veh_MuscleCar_Wheel_RL001_SimpleTown004_0.geometry}
              material={materials['SimpleTown.004']}
              position={[1.134, 0.617, -2.181]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.SR_Veh_MuscleCar_Wheel_RR001_SimpleTown004_0.geometry}
              material={materials['SimpleTown.004']}
              position={[-1.134, 0.617, -2.181]}
            />
          </group>
          <group position={[277.51, 7.47, -68.01]} rotation={[0, -0.847, 0]} scale={0.5}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.SR_Veh_StreetCar_White_SimpleTown004_0.geometry}
              material={materials['SimpleTown.004']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.SR_Veh_Wheel_FL001_SimpleTown004_0.geometry}
              material={materials['SimpleTown.004']}
              position={[1.128, 0.609, 1.839]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.SR_Veh_Wheel_FR001_SimpleTown004_0.geometry}
              material={materials['SimpleTown.004']}
              position={[-1.128, 0.609, 1.839]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.SR_Veh_Wheel_RL001_SimpleTown004_0.geometry}
              material={materials['SimpleTown.004']}
              position={[1.128, 0.609, -1.799]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.SR_Veh_Wheel_RR001_SimpleTown004_0.geometry}
              material={materials['SimpleTown.004']}
              position={[-1.128, 0.609, -1.799]}
            />
          </group>
          <group
            position={[281.8, 7.39, -58.43]}
            rotation={[-Math.PI, -1.349, Math.PI]}
            scale={0.5}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.SR_Veh_StockCar_LightBlue_SimpleTown004_0.geometry}
              material={materials['SimpleTown.004']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.SR_Veh_StockCar_Wheel_FL001_SimpleTown004_0.geometry}
              material={materials['SimpleTown.004']}
              position={[1.151, 0.564, 2.213]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.SR_Veh_StockCar_Wheel_FR001_SimpleTown004_0.geometry}
              material={materials['SimpleTown.004']}
              position={[-1.151, 0.564, 2.213]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.SR_Veh_StockCar_Wheel_RL001_SimpleTown004_0.geometry}
              material={materials['SimpleTown.004']}
              position={[1.151, 0.564, -2.102]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.SR_Veh_StockCar_Wheel_RR001_SimpleTown004_0.geometry}
              material={materials['SimpleTown.004']}
              position={[-1.151, 0.564, -2.102]}
            />
          </group>
          <group position={[167.03, 5.52, 30.2]} rotation={[3.034, -0.806, 3.098]} scale={0.5}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.SR_Veh_MuscleSports_Red_SimpleTown004_0.geometry}
              material={materials['SimpleTown.004']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.SR_Veh_MuscleSports_Wheel_FL001_SimpleTown004_0.geometry}
              material={materials['SimpleTown.004']}
              position={[1.406, 0.648, 2.482]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.SR_Veh_MuscleSports_Wheel_FR001_SimpleTown004_0.geometry}
              material={materials['SimpleTown.004']}
              position={[-1.406, 0.648, 2.482]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.SR_Veh_MuscleSports_Wheel_RL001_SimpleTown004_0.geometry}
              material={materials['SimpleTown.004']}
              position={[1.406, 0.648, -2.076]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.SR_Veh_MuscleSports_Wheel_RR001_SimpleTown004_0.geometry}
              material={materials['SimpleTown.004']}
              position={[-1.406, 0.648, -2.076]}
            />
          </group>
          <group
            position={[171.93, 5.38, 29.05]}
            rotation={[Math.PI, -0.304, -Math.PI]}
            scale={0.5}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['SR_Veh_RacingTruck_Yellow_(1)_SimpleTown004_0'].geometry}
              material={materials['SimpleTown.004']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.SR_Veh_RacingTruck_Wheel_FL_SimpleTown004_0.geometry}
              material={materials['SimpleTown.004']}
              position={[1.653, 0.831, 3.091]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.SR_Veh_RacingTruck_Wheel_FR_SimpleTown004_0.geometry}
              material={materials['SimpleTown.004']}
              position={[-1.653, 0.831, 3.091]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.SR_Veh_RacingTruck_Wheel_RL_SimpleTown004_0.geometry}
              material={materials['SimpleTown.004']}
              position={[1.204, 0.988, -3.449]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.SR_Veh_RacingTruck_Wheel_RR_SimpleTown004_0.geometry}
              material={materials['SimpleTown.004']}
              position={[-1.204, 0.988, -3.449]}
            />
          </group>
          <group position={[22.431, -7.38, -5.562]} rotation={[3.093, 0.091, 3.044]} scale={0.5}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.SR_Veh_MuscleCar_Purple_SimpleTown004_0.geometry}
              material={materials['SimpleTown.004']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.SR_Veh_MuscleCar_Wheel_FL002_SimpleTown004_0.geometry}
              material={materials['SimpleTown.004']}
              position={[1.134, 0.617, 2.521]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.SR_Veh_MuscleCar_Wheel_FR002_SimpleTown004_0.geometry}
              material={materials['SimpleTown.004']}
              position={[-1.134, 0.617, 2.521]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.SR_Veh_MuscleCar_Wheel_RL002_SimpleTown004_0.geometry}
              material={materials['SimpleTown.004']}
              position={[1.134, 0.617, -2.181]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.SR_Veh_MuscleCar_Wheel_RR002_SimpleTown004_0.geometry}
              material={materials['SimpleTown.004']}
              position={[-1.134, 0.617, -2.181]}
            />
          </group>
          <group position={[259.98, 7.57, -77.56]} rotation={[0, -0.465, 0]} scale={0.5}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.SR_Veh_RacingTruck_Black_SimpleTown004_0.geometry}
              material={materials['SimpleTown.004']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.SR_Veh_RacingTruck_Wheel_FL001_SimpleTown004_0.geometry}
              material={materials['SimpleTown.004']}
              position={[1.653, 0.831, 3.091]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.SR_Veh_RacingTruck_Wheel_FR001_SimpleTown004_0.geometry}
              material={materials['SimpleTown.004']}
              position={[-1.653, 0.831, 3.091]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.SR_Veh_RacingTruck_Wheel_RL001_SimpleTown004_0.geometry}
              material={materials['SimpleTown.004']}
              position={[1.204, 0.988, -3.449]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.SR_Veh_RacingTruck_Wheel_RR001_SimpleTown004_0.geometry}
              material={materials['SimpleTown.004']}
              position={[-1.204, 0.988, -3.449]}
            />
          </group>
          <group position={[110.2, 7.67, -134.01]} rotation={[0.132, 0.831, -0.038]} scale={0.5}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.SR_Veh_MonsterTruck_Red_SimpleTown004_0.geometry}
              material={materials['SimpleTown.004']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.SR_Veh_MonsterTruck_Wheel_FL_SimpleTown004_0.geometry}
              material={materials['SimpleTown.004']}
              position={[1.562, 1.419, 3.168]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.SR_Veh_MonsterTruck_Wheel_FR_SimpleTown004_0.geometry}
              material={materials['SimpleTown.004']}
              position={[-1.568, 1.419, 3.168]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.SR_Veh_MonsterTruck_Wheel_RL_SimpleTown004_0.geometry}
              material={materials['SimpleTown.004']}
              position={[1.568, 1.419, -3.095]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.SR_Veh_MonsterTruck_Wheel_RR_SimpleTown004_0.geometry}
              material={materials['SimpleTown.004']}
              position={[-1.562, 1.419, -3.095]}
            />
          </group>
          <group
            position={[106.971, -1.918, -125.812]}
            rotation={[0.083, -1.221, -0.122]}
            scale={0.5}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.SR_Veh_MuscleCar_Black_SimpleTown004_0.geometry}
              material={materials['SimpleTown.004']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.SR_Veh_MuscleCar_Wheel_FL003_SimpleTown004_0.geometry}
              material={materials['SimpleTown.004']}
              position={[1.134, 0.617, 2.521]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.SR_Veh_MuscleCar_Wheel_FR003_SimpleTown004_0.geometry}
              material={materials['SimpleTown.004']}
              position={[-1.134, 0.617, 2.521]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.SR_Veh_MuscleCar_Wheel_RL003_SimpleTown004_0.geometry}
              material={materials['SimpleTown.004']}
              position={[1.134, 0.617, -2.181]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.SR_Veh_MuscleCar_Wheel_RR003_SimpleTown004_0.geometry}
              material={materials['SimpleTown.004']}
              position={[-1.134, 0.617, -2.181]}
            />
          </group>
          <group position={[34.28, 5.56, -22.44]} rotation={[0.023, -0.376, 0.031]} scale={0.5}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.SR_Veh_RacingTruck_Red_SimpleTown004_0.geometry}
              material={materials['SimpleTown.004']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.SR_Veh_RacingTruck_Wheel_FL002_SimpleTown004_0.geometry}
              material={materials['SimpleTown.004']}
              position={[1.653, 0.831, 3.091]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.SR_Veh_RacingTruck_Wheel_FR002_SimpleTown004_0.geometry}
              material={materials['SimpleTown.004']}
              position={[-1.653, 0.831, 3.091]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.SR_Veh_RacingTruck_Wheel_RL002_SimpleTown004_0.geometry}
              material={materials['SimpleTown.004']}
              position={[1.204, 0.988, -3.449]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.SR_Veh_RacingTruck_Wheel_RR002_SimpleTown004_0.geometry}
              material={materials['SimpleTown.004']}
              position={[-1.204, 0.988, -3.449]}
            />
          </group>
          <group position={[-28.339, -7.438, 19.878]} rotation={[3.127, -0.846, 3.13]} scale={0.5}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.SR_Veh_RacingTruck_Yellow_SimpleTown004_0.geometry}
              material={materials['SimpleTown.004']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.SR_Veh_RacingTruck_Wheel_FL003_SimpleTown004_0.geometry}
              material={materials['SimpleTown.004']}
              position={[1.653, 0.831, 3.091]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.SR_Veh_RacingTruck_Wheel_FR003_SimpleTown004_0.geometry}
              material={materials['SimpleTown.004']}
              position={[-1.653, 0.831, 3.091]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.SR_Veh_RacingTruck_Wheel_RL003_SimpleTown004_0.geometry}
              material={materials['SimpleTown.004']}
              position={[1.204, 0.988, -3.449]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.SR_Veh_RacingTruck_Wheel_RR003_SimpleTown004_0.geometry}
              material={materials['SimpleTown.004']}
              position={[-1.204, 0.988, -3.449]}
            />
          </group>
          <group position={[107.025, 7.557, -126.44]} rotation={[1.749, 1.495, -1.707]} scale={0.5}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['SR_Veh_OffRoadTruck_Yellow_(1)_SimpleTown004_0'].geometry}
              material={materials['SimpleTown.004']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.SR_Veh_OffRoadTruck_Wheel_FL001_SimpleTown004_0.geometry}
              material={materials['SimpleTown.004']}
              position={[1.245, 0.921, 2.744]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.SR_Veh_OffRoadTruck_Wheel_FR001_SimpleTown004_0.geometry}
              material={materials['SimpleTown.004']}
              position={[-1.246, 0.921, 2.744]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.SR_Veh_OffRoadTruck_Wheel_RL001_SimpleTown004_0.geometry}
              material={materials['SimpleTown.004']}
              position={[1.245, 0.921, -2.581]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.SR_Veh_OffRoadTruck_Wheel_RR001_SimpleTown004_0.geometry}
              material={materials['SimpleTown.004']}
              position={[-1.246, 0.921, -2.581]}
            />
          </group>
          <group position={[288.21, 4.25, 27.57]} rotation={[0.013, -0.041, -0.02]} scale={0.5}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['SR_Veh_MonsterTruck_Red_(1)_SimpleTown004_0'].geometry}
              material={materials['SimpleTown.004']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.SR_Veh_MonsterTruck_Wheel_FL001_SimpleTown004_0.geometry}
              material={materials['SimpleTown.004']}
              position={[1.562, 1.419, 3.168]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.SR_Veh_MonsterTruck_Wheel_FR001_SimpleTown004_0.geometry}
              material={materials['SimpleTown.004']}
              position={[-1.568, 1.419, 3.168]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.SR_Veh_MonsterTruck_Wheel_RL001_SimpleTown004_0.geometry}
              material={materials['SimpleTown.004']}
              position={[1.568, 1.419, -3.095]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.SR_Veh_MonsterTruck_Wheel_RR001_SimpleTown004_0.geometry}
              material={materials['SimpleTown.004']}
              position={[-1.562, 1.419, -3.095]}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes.SPW_Vehicle_Land_Static_Fire_Truck_SPW_Vehicle_Land_Fire_Truck_0.geometry
            }
            material={materials.SPW_Vehicle_Land_Fire_Truck}
            position={[258, 7.68, -85.98]}
            rotation={[0, -0.693, 0]}
            scale={0.9}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes['SPW_Vehicle_Land_Static_Ambulance_(1)_SPW_Vehicle_Land_Ambulance_0'].geometry
            }
            material={materials.SPW_Vehicle_Land_Ambulance}
            position={[284.14, 7.17, -47.58]}
            rotation={[0.042, -0.268, -0.001]}
            scale={0.87}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes
                .SPW_Vehicle_Land_Static_Truck_Empty_Color03_SPW_Vehicle_Land_Truck_Empty_Color03_0
                .geometry
            }
            material={materials.SPW_Vehicle_Land_Truck_Empty_Color03}
            position={[327.96, 6.85, -24.6]}
            rotation={[0, -0.855, 0]}
            scale={0.9}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes['SPW_Vehicle_Land_Static_Ambulance_(2)_SPW_Vehicle_Land_Ambulance_0'].geometry
            }
            material={materials.SPW_Vehicle_Land_Ambulance}
            position={[19.78, 4.243, 13.606]}
            rotation={[-3.134, -0.16, 3.085]}
            scale={0.87}
          />
        </group>
        <group position={[-95.666, -18.442, -10.755]}>
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes['SPW_Urban_Road_Props_Traffic_Cone_(1)_SPW_Urban_Road_Props_01001_0'].geometry
            }
            material={materials['SPW_Urban_Road_Props_01.001']}
            position={[50.51, 20.165, 34.506]}
            rotation={[-0.01, 0.842, 0.035]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes['SPW_Urban_Road_Props_Traffic_Cone_(2)_SPW_Urban_Road_Props_01001_0'].geometry
            }
            material={materials['SPW_Urban_Road_Props_01.001']}
            position={[47.997, 20.12, 33.777]}
            rotation={[-0.021, 1.011, 0.044]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes['SPW_Urban_Road_Props_Traffic_Cone_(3)_SPW_Urban_Road_Props_01001_0'].geometry
            }
            material={materials['SPW_Urban_Road_Props_01.001']}
            position={[46.1, 20.1, 32.05]}
            rotation={[-0.021, 1.011, 0.044]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes['SPW_Urban_Road_Props_Traffic_Cone_(4)_SPW_Urban_Road_Props_01001_0'].geometry
            }
            material={materials['SPW_Urban_Road_Props_01.001']}
            position={[43.51, 20.06, 31.09]}
            rotation={[-0.09, 1.354, 0.109]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes['SPW_Urban_Road_Props_Traffic_Cone_(5)_SPW_Urban_Road_Props_01001_0'].geometry
            }
            material={materials['SPW_Urban_Road_Props_01.001']}
            position={[40.7, 20.01, 30.13]}
            rotation={[-0.09, 1.354, 0.109]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes['SPW_Urban_Road_Props_Traffic_Cone_(6)_SPW_Urban_Road_Props_01001_0'].geometry
            }
            material={materials['SPW_Urban_Road_Props_01.001']}
            position={[37.59, 19.96, 29.61]}
            rotation={[-0.09, 1.354, 0.109]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes['SPW_Urban_Road_Props_Traffic_Cone_(7)_SPW_Urban_Road_Props_01001_0'].geometry
            }
            material={materials['SPW_Urban_Road_Props_01.001']}
            position={[34.19, 19.9, 29.27]}
            rotation={[-1.239, 1.546, 1.256]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes['SPW_Urban_Road_Props_Traffic_Cone_(8)_SPW_Urban_Road_Props_01001_0'].geometry
            }
            material={materials['SPW_Urban_Road_Props_01.001']}
            position={[30.71, 19.89, 29.2]}
            rotation={[-1.239, 1.546, 1.256]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes['SPW_Urban_Road_Props_Traffic_Cone_(9)_SPW_Urban_Road_Props_01001_0'].geometry
            }
            material={materials['SPW_Urban_Road_Props_01.001']}
            position={[27.19, 19.92, 29.39]}
            rotation={[-1.239, 1.546, 1.256]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes['SPW_Urban_Road_Props_Traffic_Cone_(10)_SPW_Urban_Road_Props_01001_0'].geometry
            }
            material={materials['SPW_Urban_Road_Props_01.001']}
            position={[23.59, 19.96, 30.1]}
            rotation={[-1.239, 1.546, 1.256]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes['SPW_Urban_Road_Props_Traffic_Cone_(11)_SPW_Urban_Road_Props_01001_0'].geometry
            }
            material={materials['SPW_Urban_Road_Props_01.001']}
            position={[21.91, 20.038, 31.5]}
            rotation={[-1.239, 1.546, 1.256]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes['SPW_Urban_Road_Props_Traffic_Cone_(12)_SPW_Urban_Road_Props_01001_0'].geometry
            }
            material={materials['SPW_Urban_Road_Props_01.001']}
            position={[18.705, 20.099, 31.911]}
            rotation={[-1.239, 1.546, 1.256]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes['SPW_Urban_Road_Props_Traffic_Cone_(13)_SPW_Urban_Road_Props_01001_0'].geometry
            }
            material={materials['SPW_Urban_Road_Props_01.001']}
            position={[49.921, 20.188, 4.199]}
            rotation={[-1.248, -1.546, -1.231]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes['SPW_Urban_Road_Props_Traffic_Cone_(14)_SPW_Urban_Road_Props_01001_0'].geometry
            }
            material={materials['SPW_Urban_Road_Props_01.001']}
            position={[47.54, 20.12, 7.26]}
            rotation={[-1.248, -1.546, -1.231]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes['SPW_Urban_Road_Props_Traffic_Cone_(15)_SPW_Urban_Road_Props_01001_0'].geometry
            }
            material={materials['SPW_Urban_Road_Props_01.001']}
            position={[44.86, 20.08, 8.03]}
            rotation={[-1.248, -1.546, -1.231]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes['SPW_Urban_Road_Props_Traffic_Cone_(16)_SPW_Urban_Road_Props_01001_0'].geometry
            }
            material={materials['SPW_Urban_Road_Props_01.001']}
            position={[41.27, 20.02, 8.79]}
            rotation={[-1.248, -1.546, -1.231]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes['SPW_Urban_Road_Props_Traffic_Cone_(17)_SPW_Urban_Road_Props_01001_0'].geometry
            }
            material={materials['SPW_Urban_Road_Props_01.001']}
            position={[37.76, 19.95, 9.04]}
            rotation={[-1.248, -1.546, -1.231]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes['SPW_Urban_Road_Props_Traffic_Cone_(18)_SPW_Urban_Road_Props_01001_0'].geometry
            }
            material={materials['SPW_Urban_Road_Props_01.001']}
            position={[34.306, 19.96, 9.02]}
            rotation={[1.267, -1.545, 1.284]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes['SPW_Urban_Road_Props_Traffic_Cone_(19)_SPW_Urban_Road_Props_01001_0'].geometry
            }
            material={materials['SPW_Urban_Road_Props_01.001']}
            position={[30.87, 19.907, 8.74]}
            rotation={[-3.045, -1.37, -3.026]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes['SPW_Urban_Road_Props_Traffic_Cone_(20)_SPW_Urban_Road_Props_01001_0'].geometry
            }
            material={materials['SPW_Urban_Road_Props_01.001']}
            position={[27.75, 19.909, 7.992]}
            rotation={[-3.045, -1.37, -3.026]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes['SPW_Urban_Road_Props_Traffic_Cone_(21)_SPW_Urban_Road_Props_01001_0'].geometry
            }
            material={materials['SPW_Urban_Road_Props_01.001']}
            position={[24.93, 19.946, 6.869]}
            rotation={[-3.045, -1.37, -3.026]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes['SPW_Urban_Road_Props_Traffic_Cone_(22)_SPW_Urban_Road_Props_01001_0'].geometry
            }
            material={materials['SPW_Urban_Road_Props_01.001']}
            position={[22.328, 20.01, 4.351]}
            rotation={[-3.12, -1.027, -3.123]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes['SPW_Urban_Road_Props_Traffic_Cone_(23)_SPW_Urban_Road_Props_01001_0'].geometry
            }
            material={materials['SPW_Urban_Road_Props_01.001']}
            position={[20.02, 20.14, 4.24]}
            rotation={[-3.12, -1.027, -3.097]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes['SPW_Urban_Road_Props_Traffic_Cone_(24)_SPW_Urban_Road_Props_01001_0'].geometry
            }
            material={materials['SPW_Urban_Road_Props_01.001']}
            position={[17.87, 20.09, 3.19]}
            rotation={[-3.132, -0.858, -3.106]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes['SPW_Urban_Road_Props_Traffic_Cone_(25)_SPW_Urban_Road_Props_01001_0'].geometry
            }
            material={materials['SPW_Urban_Road_Props_01.001']}
            position={[-25.278, 20.109, -13.917]}
            rotation={[0.155, -1.187, 0.135]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes['SPW_Urban_Road_Props_Traffic_Cone_(26)_SPW_Urban_Road_Props_01001_0'].geometry
            }
            material={materials['SPW_Urban_Road_Props_01.001']}
            position={[-38.926, 19.403, 0.296]}
            rotation={[-0.002, -0.197, 0.043]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes['SPW_Urban_Road_Props_Traffic_Cone_(27)_SPW_Urban_Road_Props_01001_0'].geometry
            }
            material={materials['SPW_Urban_Road_Props_01.001']}
            position={[-62.983, 19.557, 51.596]}
            rotation={[0.012, -0.495, 0.015]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes['SPW_Urban_Road_Props_Traffic_Cone_(28)_SPW_Urban_Road_Props_01001_0'].geometry
            }
            material={materials['SPW_Urban_Road_Props_01.001']}
            position={[-73.591, 19.388, 71.1]}
            rotation={[0.012, -0.495, 0.01]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes['SPW_Urban_Road_Props_Traffic_Cone_(29)_SPW_Urban_Road_Props_01001_0'].geometry
            }
            material={materials['SPW_Urban_Road_Props_01.001']}
            position={[-57.995, 18.173, 115.065]}
            rotation={[0.018, -0.842, 0.014]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes['SPW_Urban_Road_Props_Traffic_Cone_(30)_SPW_Urban_Road_Props_01001_0'].geometry
            }
            material={materials['SPW_Urban_Road_Props_01.001']}
            position={[-36.613, 18.211, 119.422]}
            rotation={[0.035, -1.252, 0.029]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes['SPW_Urban_Road_Props_Traffic_Cone_(31)_SPW_Urban_Road_Props_01001_0'].geometry
            }
            material={materials['SPW_Urban_Road_Props_01.001']}
            position={[172.596, 19.971, 24.739]}
            rotation={[-0.021, 1.011, -0.039]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes['SPW_Urban_Road_Props_Traffic_Cone_(32)_SPW_Urban_Road_Props_01001_0'].geometry
            }
            material={materials['SPW_Urban_Road_Props_01.001']}
            position={[183.835, 20.406, 49.744]}
            rotation={[0.063, 1.396, -0.096]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes['SPW_Urban_Road_Props_Traffic_Cone_(33)_SPW_Urban_Road_Props_01001_0'].geometry
            }
            material={materials['SPW_Urban_Road_Props_01.001']}
            position={[75.673, 21.184, 87.348]}
            rotation={[0.017, 1.242, -0.052]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes['SPW_Urban_Road_Props_Traffic_Cone_(34)_SPW_Urban_Road_Props_01001_0'].geometry
            }
            material={materials['SPW_Urban_Road_Props_01.001']}
            position={[73.047, 21.78, 111.28]}
            rotation={[2.897, 1.362, -2.934]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes['SPW_Urban_Road_Props_Traffic_Cone_(35)_SPW_Urban_Road_Props_01001_0'].geometry
            }
            material={materials['SPW_Urban_Road_Props_01.001']}
            position={[163.103, 20.486, 85.782]}
            rotation={[3.098, 1.113, 3.111]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes['SPW_Urban_Road_Props_Traffic_Cone_(36)_SPW_Urban_Road_Props_01001_0'].geometry
            }
            material={materials['SPW_Urban_Road_Props_01.001']}
            position={[191.407, 20.671, 84.356]}
            rotation={[3.074, 0.239, -3.116]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes['SPW_Urban_Road_Props_Traffic_Cone_(37)_SPW_Urban_Road_Props_01001_0'].geometry
            }
            material={materials['SPW_Urban_Road_Props_01.001']}
            position={[251.69, 18.17, 100.49]}
            rotation={[3.098, 1.014, 3.121]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes['SPW_Urban_Road_Props_Traffic_Cone_(38)_SPW_Urban_Road_Props_01001_0'].geometry
            }
            material={materials['SPW_Urban_Road_Props_01.001']}
            position={[254.603, 18.239, 80.536]}
            rotation={[-3.03, 0.953, 3.029]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes['SPW_Urban_Road_Props_Traffic_Cone_(39)_SPW_Urban_Road_Props_01001_0'].geometry
            }
            material={materials['SPW_Urban_Road_Props_01.001']}
            position={[184.655, 21.682, -15.161]}
            rotation={[-3.065, 0.686, 3.06]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes['SPW_Urban_Road_Props_Traffic_Cone_(40)_SPW_Urban_Road_Props_01001_0'].geometry
            }
            material={materials['SPW_Urban_Road_Props_01.001']}
            position={[158.335, 21.217, -26.009]}
            rotation={[-3.095, 0.077, 3.077]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes['SPW_Urban_Road_Props_Traffic_Cone_(41)_SPW_Urban_Road_Props_01001_0'].geometry
            }
            material={materials['SPW_Urban_Road_Props_01.001']}
            position={[106.267, 21.617, 17.056]}
            rotation={[-3.095, 0.077, 3.132]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes['SPW_Urban_Road_Props_Traffic_Cone_(42)_SPW_Urban_Road_Props_01001_0'].geometry
            }
            material={materials['SPW_Urban_Road_Props_01.001']}
            position={[84.966, 21.265, 4.948]}
            rotation={[-3.082, 0.99, 3.098]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes['SPW_Urban_Road_Props_Traffic_Cone_(43)_SPW_Urban_Road_Props_01001_0'].geometry
            }
            material={materials['SPW_Urban_Road_Props_01.001']}
            position={[122.776, 21.839, -96.826]}
            rotation={[-3.115, 0.726, 3.121]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes['SPW_Urban_Road_Props_Traffic_Cone_(44)_SPW_Urban_Road_Props_01001_0'].geometry
            }
            material={materials['SPW_Urban_Road_Props_01.001']}
            position={[95.631, 21.599, -105.029]}
            rotation={[-3.121, -0.122, 3.117]}
          />
        </group>
        <group position={[-139.949, 5.902, -34.08]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['uluru_-_dingosign_SPW_Urban_Road_Props_03001_0'].geometry}
            material={materials['SPW_Urban_Road_Props_03.001']}
            position={[-12.078, -2.998, -3.494]}
            rotation={[0.003, 0.814, 0.817]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['uluru_-_dingofence_MountainsPalette001_0'].geometry}
            material={materials['MountainsPalette.001']}
            position={[25.73, -4.93, -31.07]}
            rotation={[0.025, 0.528, 0.004]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['uluru_-_dingofence001_MountainsPalette001_0'].geometry}
            material={materials['MountainsPalette.001']}
            position={[41.76, -8.03, -67]}
            rotation={[0.554, 1.5, -0.629]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['uluru_-_dingofence002_MountainsPalette001_0'].geometry}
            material={materials['MountainsPalette.001']}
            position={[0.11, -4.06, -14.61]}
            rotation={[-0.008, 0.7, 0.002]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['uluru_-_dingofence003_MountainsPalette001_0'].geometry}
            material={materials['MountainsPalette.001']}
            position={[33.09, -5.27, -37.8]}
            rotation={[0.053, 0.931, -0.13]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['uluru_-_dingofence004_MountainsPalette001_0'].geometry}
            material={materials['MountainsPalette.001']}
            position={[40.15, -7.21, -56.96]}
            rotation={[0.082, 1.309, -0.162]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['uluru_-_dingofence005_MountainsPalette001_0'].geometry}
            material={materials['MountainsPalette.001']}
            position={[-41.53, -3.89, 13.18]}
            rotation={[-0.038, 0.09, -0.004]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['uluru_-_dingofence006_MountainsPalette001_0'].geometry}
            material={materials['MountainsPalette.001']}
            position={[-7.49, -4.16, -7.77]}
            rotation={[-0.01, 0.737, 0.028]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['uluru_-_dingofence007_MountainsPalette001_0'].geometry}
            material={materials['MountainsPalette.001']}
            position={[37.56, -6.28, -47.09]}
            rotation={[0.055, 1.257, -0.109]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['uluru_-_dingofence008_MountainsPalette001_0'].geometry}
            material={materials['MountainsPalette.001']}
            position={[-22.73, -4.25, 5.73]}
            rotation={[-0.015, 0.585, -0.047]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['uluru_-_dingofence009_MountainsPalette001_0'].geometry}
            material={materials['MountainsPalette.001']}
            position={[16.86, -4.92, -25.88]}
            rotation={[0.025, 0.528, -0.031]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['uluru_-_dingofence010_MountainsPalette001_0'].geometry}
            material={materials['MountainsPalette.001']}
            position={[-14.86, -4.38, -0.77]}
            rotation={[0, 0.804, 0.013]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['uluru_-_dingofence011_MountainsPalette001_0'].geometry}
            material={materials['MountainsPalette.001']}
            position={[-31.79, -3.83, 10.71]}
            rotation={[-0.022, 0.442, -0.017]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['uluru_-_dingofence012_MountainsPalette001_0'].geometry}
            material={materials['MountainsPalette.001']}
            position={[8.24, -4.44, -20.58]}
            rotation={[0.025, 0.528, -0.042]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['uluru_-_dingofence_(1)_MountainsPalette001_0'].geometry}
            material={materials['MountainsPalette.001']}
            position={[-52, -4.02, 14.1]}
            rotation={[-0.038, 0.09, -0.004]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['uluru_-_dingofence_(2)_MountainsPalette001_0'].geometry}
            material={materials['MountainsPalette.001']}
            position={[-62.4, -3.27, 14.98]}
            rotation={[-0.038, 0.09, -0.137]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['uluru_-_dingofence_(3)_MountainsPalette001_0'].geometry}
            material={materials['MountainsPalette.001']}
            position={[-72.6, -1.98, 15.85]}
            rotation={[-0.038, 0.09, -0.104]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['uluru_-_dingosign_(1)_SPW_Urban_Road_Props_03001_0'].geometry}
            material={materials['SPW_Urban_Road_Props_03.001']}
            position={[1.17, -2.749, -15.406]}
            rotation={[0.013, 0.658, 0.865]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['dingo_(1)_MountainsPalette001_0'].geometry}
            material={materials['MountainsPalette.001']}
            position={[-9.539, -3.713, -10.411]}
            rotation={[-1.634, 0.059, -0.339]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['dingo_(2)_MountainsPalette001_0'].geometry}
            material={materials['MountainsPalette.001']}
            position={[-9.237, -4.176, -14.404]}
            rotation={[-1.693, -0.038, 0.777]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.dingo_MountainsPalette001_0.geometry}
            material={materials['MountainsPalette.001']}
            position={[-18.221, -3.789, -3.253]}
            rotation={[-1.533, 0.085, 0.869]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.camelskeleton_MountainsPalette001_0.geometry}
            material={materials['MountainsPalette.001']}
            position={[-14.97, -4.03, -3.89]}
            rotation={[-1.511, -0.024, 1.083]}
            scale={1.23}
          />
        </group>
        <group position={[48.449, 17.196, -29.006]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Au_baobab02_MountainsPalette002_0.geometry}
            material={materials['MountainsPalette.002']}
            position={[13.65, -13.28, -31.69]}
            rotation={[-Math.PI / 2, 0, 1.84]}
            scale={[1, 1, 0.956]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Au_baobab01_MountainsPalette002_0.geometry}
            material={materials['MountainsPalette.002']}
            position={[18.251, -12.86, -32.994]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[1.16, 1, 1]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Au_baobab02_(1)_MountainsPalette002_0'].geometry}
            material={materials['MountainsPalette.002']}
            position={[-17, -15.35, -15.7]}
            rotation={[-Math.PI / 2, 0, 0.362]}
            scale={0.746}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Au_baobab01_(1)_MountainsPalette002_0'].geometry}
            material={materials['MountainsPalette.002']}
            position={[-23.05, -15.41, -6.51]}
            rotation={[-Math.PI / 2, 0, -1.478]}
            scale={0.649}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Au_baobab01_(2)_MountainsPalette002_0'].geometry}
            material={materials['MountainsPalette.002']}
            position={[-14.8, -15.52, -22.47]}
            rotation={[-Math.PI / 2, 0, 0.829]}
            scale={0.808}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Au_baobab02_(2)_MountainsPalette002_0'].geometry}
            material={materials['MountainsPalette.002']}
            position={[26.13, -13.28, -28.74]}
            rotation={[-Math.PI / 2, 0, -2.607]}
            scale={0.758}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Au_baobab01_(3)_MountainsPalette002_0'].geometry}
            material={materials['MountainsPalette.002']}
            position={[4.22, -16.26, -19.01]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[0.698, 0.698, 0.772]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Au_baobab02_(3)_MountainsPalette002_0'].geometry}
            material={materials['MountainsPalette.002']}
            position={[32.23, -14.44, 142.27]}
            rotation={[-Math.PI / 2, 0, -1.136]}
            scale={[1, 1, 0.956]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Au_baobab01_(4)_MountainsPalette002_0'].geometry}
            material={materials['MountainsPalette.002']}
            position={[55.1, -12.1, 164.7]}
            rotation={[-Math.PI / 2, 0, -2.147]}
            scale={0.808}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Au_baobab01_(5)_MountainsPalette002_0'].geometry}
            material={materials['MountainsPalette.002']}
            position={[42.15, -14.19, 151.26]}
            rotation={[-Math.PI / 2, 0, -2.976]}
            scale={[0.698, 0.698, 0.772]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Au_baobab01_(6)_MountainsPalette002_0'].geometry}
            material={materials['MountainsPalette.002']}
            position={[51.89, -14.71, 151.28]}
            rotation={[-Math.PI / 2, 0, 1.829]}
            scale={0.649}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Au_baobab02_(4)_MountainsPalette002_0'].geometry}
            material={materials['MountainsPalette.002']}
            position={[51.36, -15.02, 143.66]}
            rotation={[-1.571, 0, -2.614]}
            scale={0.746}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Au_baobab02_(5)_MountainsPalette002_0'].geometry}
            material={materials['MountainsPalette.002']}
            position={[3.8, -14.35, 154.97]}
            rotation={[-Math.PI / 2, 0, 0.7]}
            scale={0.932}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Au_baobab01_(7)_MountainsPalette002_0'].geometry}
            material={materials['MountainsPalette.002']}
            position={[26.53, -14.04, 140.97]}
            rotation={[-Math.PI / 2, 0, -2.976]}
            scale={[1.16, 1, 1]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Au_baobab01_(8)_MountainsPalette002_0'].geometry}
            material={materials['MountainsPalette.002']}
            position={[45.66, -15.68, 135.48]}
            rotation={[-1.622, -0.004, 0.205]}
            scale={0.775}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Au_baobab01_(9)_MountainsPalette002_0'].geometry}
            material={materials['MountainsPalette.002']}
            position={[7.15, -10.86, 173.18]}
            rotation={[-Math.PI / 2, 0, 0.33]}
            scale={1.16}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Au_baobab01_(10)_MountainsPalette002_0'].geometry}
            material={materials['MountainsPalette.002']}
            position={[-6.84, -15, 159.78]}
            rotation={[-Math.PI / 2, 0, 0.33]}
            scale={[0.698, 0.698, 0.772]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Au_baobab02_(6)_MountainsPalette002_0'].geometry}
            material={materials['MountainsPalette.002']}
            position={[0.86, -11.87, 170.68]}
            rotation={[-Math.PI / 2, 0, 2.171]}
            scale={1.211}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Au_baobab02_(7)_MountainsPalette002_0'].geometry}
            material={materials['MountainsPalette.002']}
            position={[-178.8, -19.3, 113.6]}
            rotation={[-Math.PI / 2, 0, -2.091]}
            scale={1.211}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Au_baobab01_(11)_MountainsPalette002_0'].geometry}
            material={materials['MountainsPalette.002']}
            position={[-182.35, -19.51, 106.74]}
            rotation={[-Math.PI / 2, 0, 2.352]}
            scale={1.16}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Au_baobab01_(12)_MountainsPalette002_0'].geometry}
            material={materials['MountainsPalette.002']}
            position={[-178, -18.5, 125]}
            rotation={[-Math.PI / 2, 0, 2.352]}
            scale={[0.698, 0.698, 0.772]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Au_baobab01_(13)_MountainsPalette002_0'].geometry}
            material={materials['MountainsPalette.002']}
            position={[-194.277, -18.65, 126.258]}
            rotation={[-Math.PI / 2, 0, 0.826]}
            scale={[0.539, 0.539, 0.596]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Au_baobab02_(8)_MountainsPalette002_0'].geometry}
            material={materials['MountainsPalette.002']}
            position={[-191.37, -18.64, 115.03]}
            rotation={[-Math.PI / 2, 0, 1.779]}
            scale={0.956}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Au_baobab01_(14)_MountainsPalette002_0'].geometry}
            material={materials['MountainsPalette.002']}
            position={[-111.07, -16.4, -14.1]}
            rotation={[-Math.PI / 2, 0, -0.081]}
            scale={1.16}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Au_baobab02_(9)_MountainsPalette002_0'].geometry}
            material={materials['MountainsPalette.002']}
            position={[-120.25, -16.2, -14.01]}
            rotation={[-Math.PI / 2, 0, 1.759]}
            scale={1.211}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Au_baobab01_(15)_MountainsPalette002_0'].geometry}
            material={materials['MountainsPalette.002']}
            position={[-111.59, -15.4, -21.41]}
            rotation={[-Math.PI / 2, 0, -0.081]}
            scale={[0.698, 0.698, 0.772]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Au_baobab02_(10)_MountainsPalette002_0'].geometry}
            material={materials['MountainsPalette.002']}
            position={[-106.654, -16.224, -10.392]}
            rotation={[-1.509, 0.08, -0.657]}
            scale={0.956}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Au_baobab01_(16)_MountainsPalette002_0'].geometry}
            material={materials['MountainsPalette.002']}
            position={[-106.75, -15.22, -36.9]}
            rotation={[-Math.PI / 2, 0, 2.009]}
            scale={[1.033, 1.033, 1.143]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Au_baobab02_(11)_MountainsPalette002_0'].geometry}
            material={materials['MountainsPalette.002']}
            position={[93.94, -19.04, 99.04]}
            rotation={[-Math.PI / 2, 0, -2.789]}
            scale={1.211}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Au_baobab01_(17)_MountainsPalette002_0'].geometry}
            material={materials['MountainsPalette.002']}
            position={[77.17, -17.59, 89]}
            rotation={[-Math.PI / 2, 0, 1.027]}
            scale={[0.698, 0.698, 0.772]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Au_baobab02_(12)_MountainsPalette002_0'].geometry}
            material={materials['MountainsPalette.002']}
            position={[85, -18.38, 87.9]}
            rotation={[-Math.PI / 2, 0, -0.287]}
            scale={0.932}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.BaobabBig_MountainsPalette002_0.geometry}
            material={materials['MountainsPalette.002']}
            position={[-78.552, -15.176, 43.689]}
            rotation={[-Math.PI, 0.455, -Math.PI]}
            scale={2.6}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Base_SPW_Urban_Road_Props_01_0.geometry}
          material={materials.SPW_Urban_Road_Props_01}
          position={[319.9, 17.2, -18.4]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object001_SPW_Urban_Road_Props_01_0.geometry}
          material={materials.SPW_Urban_Road_Props_01}
          position={[0, 19, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SPW_Urban_Bldg_17_Color02_SPW_Urban_Bldg_17_Color02_0.geometry}
          material={materials.SPW_Urban_Bldg_17_Color02}
          position={[12.2, 18.2, 181.8]}
          rotation={[-1.592, -0.017, -2.375]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SPW_Urban_Train_Station_Props_02_SPW_Urban_Train_Station_0.geometry}
          material={materials.SPW_Urban_Train_Station}
          position={[74.54, 14.46, 192.47]}
          rotation={[-1.56, -0.039, -1.699]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SR_Bld_Stands__1__SimpleTown_0.geometry}
          material={materials.SimpleTown}
          position={[-18.3, 15.7, -14.2]}
          rotation={[-1.576, -0.006, 0.825]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SR_Bld_Stands__4__SimpleTown_0.geometry}
          material={materials.SimpleTown}
          position={[-3.022, 11.109, 151.537]}
          rotation={[-1.541, 0.01, 0.413]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SR_Bld_Stands__5__SimpleTown_0.geometry}
          material={materials.SimpleTown}
          position={[123.16, 12.54, 38.55]}
          rotation={[-1.591, 0.025, 2.264]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SR_Bld_Stands_Crowd_00_SimpleTown_0.geometry}
          material={materials.SimpleTown}
          position={[-138.454, 12.2, 5.342]}
          rotation={[-Math.PI / 2, 0, 0.454]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SR_Bld_Stands_Crowd_02_SimpleTown_0.geometry}
          material={materials.SimpleTown}
          position={[-1.1, 15.5, 34.2]}
          rotation={[-1.576, 0.003, 0.492]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SR_Bld_Stands_Crowd_02a_SimpleTown_0.geometry}
          material={materials.SimpleTown}
          position={[-138.454, 12, 5.342]}
          rotation={[-Math.PI / 2, 0, 0.454]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SR_Bld_Tent_Shop_Blue_SimpleTown_0.geometry}
          material={materials.SimpleTown}
          position={[67.4, 10.8, -65.5]}
          rotation={[-1.575, 0.01, -1.19]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SR_Prop_FlagTower_SimpleTown_0.geometry}
          material={materials.SimpleTown}
          position={[-161.853, 10.5, -126.396]}
          rotation={[-Math.PI / 2, 0, -0.353]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SR_Prop_FlagTower__1__SimpleTown_0.geometry}
          material={materials.SimpleTown}
          position={[7.19, 10.81, 140.44]}
          rotation={[-Math.PI / 2, 0, 3.094]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SR_Bld_Pitstop_Large_SimpleTown_0.geometry}
          material={materials.SimpleTown}
          position={[131.219, 3.46, -20.696]}
          rotation={[0.015, -0.76, 0]}
          scale={0.6}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['SR_Bld_Tent_Shop_Blue_(1)_SimpleTown_0'].geometry}
          material={materials.SimpleTown}
          position={[-114.26, 17.32, -126.61]}
          rotation={[-1.526, 0.009, -1.998]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['SR_Bld_Stands__1__(1)_SimpleTown_0'].geometry}
          material={materials.SimpleTown}
          position={[-106.04, 17.51, -83.73]}
          rotation={[-1.567, 0.004, 2.463]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['SR_Prop_FlagTower__1__(1)_SimpleTown_0'].geometry}
          material={materials.SimpleTown}
          position={[196.671, 8.916, 61.993]}
          rotation={[-1.535, 0.016, -1.143]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fence_MiscTrack001_0.geometry}
          material={materials['MiscTrack.001']}
          position={[-8.416, 0, 21.649]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tires01_TiresRW_0.geometry}
          material={materials.TiresRW}
          position={[161.591, 1.836, 84.419]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tires002_TiresRW_0.geometry}
          material={materials.TiresRW}
          position={[3.896, 3.593, 103.66]}
          rotation={[-Math.PI / 2, 0, -1.805]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tires003_TiresRW_0.geometry}
          material={materials.TiresRW}
          position={[-144.744, 1.836, 110.122]}
          rotation={[-Math.PI / 2, 0, -1.466]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tires004_TiresRW_0.geometry}
          material={materials.TiresRW}
          position={[6.262, 3.98, -95.19]}
          rotation={[-Math.PI / 2, 0, 1.828]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SR_Prop_Barrier_Concrete_01_SimpleTown002_0.geometry}
          material={materials['SimpleTown.002']}
          position={[-155, 1.41, -33.95]}
          rotation={[3.071, 1.518, -2.998]}
          scale={0.5}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['SR_Prop_Barrier_Concrete_01_(1)_SimpleTown002_0'].geometry}
          material={materials['SimpleTown.002']}
          position={[-126.98, 1.72, -52.18]}
          rotation={[-3.057, 0.012, 3.075]}
          scale={0.5}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Asphalt01_MiscTrack002_0.geometry}
          material={materials['MiscTrack.002']}
          position={[-8.416, 0, 21.649]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Asphalt02_MiscTrack002_0.geometry}
          material={materials['MiscTrack.002']}
          position={[-8.416, 0, 21.649]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Kerbs01_MiscTrack002_0.geometry}
          material={materials['MiscTrack.002']}
          position={[-8.416, 0, 21.649]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.kerbs02_MiscTrack002_0.geometry}
          material={materials['MiscTrack.002']}
          position={[-8.416, 0, 21.649]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Road_road_asphalt01_0.geometry}
          material={materials.road_asphalt01}
          position={[-8.416, 0, 21.649]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sands_MountainsPalette_0.geometry}
          material={materials.MountainsPalette}
          position={[0.001, -81.592, -2.527]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Uluru_mountain_MountainsPalette_0.geometry}
          material={materials.MountainsPalette}
          position={[-753.465, -7.725, 694.806]}
          rotation={[0.288, -1.471, 0.26]}
          scale={0.089}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['uluru_-_start_SimpleTown003_0'].geometry}
          material={materials['SimpleTown.003']}
          position={[123.284, 2.59, 19.988]}
          rotation={[-Math.PI / 2, 0, 0.826]}
        />
      </group>
    </group>
  )
}

// useGLTF.preload('/drift_clash_uluru.glb')