/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: amogusstrikesback2 (https://sketchfab.com/amogusstrikesback2)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sports-car-racing-paris-1a2b3ec183c44870896c3e2d9aa6e146
Title: sports car racing paris
*/

import { useGLTF } from "@react-three/drei";
import ET from "/ParisScene/EiffelTower.glb";

export default function EiffelTower(props) {
  const { nodes, materials } = useGLTF(ET);
  return (
    <group {...props} dispose={null} scale={0.1} ref={props.innerRef}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.aifeiertieta_1_D_aifeiertieta_1_0.geometry}
        material={materials["D_aifeiertieta_1.001"]}
        rotation={[-Math.PI / 2, 0, -1.755]}
      />
    </group>
  );
}
