/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import newground from "/ParisScene/Newground.glb";

export function Newground(props) {
  const { nodes, materials } = useGLTF(newground);
  return (
    <group {...props} dispose={null} scale={6.9}>
      <group scale={0.01}>
        <group position={[510.159, 17.934, 88.038]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.dibiao_28_D_dibiao_9_0.geometry}
            material={materials.D_dibiao_9}
            position={[-510.159, -17.934, -88.038]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.dibiao_29_D_dibiao_9_0.geometry}
            material={materials.D_dibiao_9}
            position={[-510.159, -17.934, -88.038]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.dibiao_30_D_dibiao_8_0.geometry}
            material={materials.D_dibiao_8}
            position={[-510.159, -17.934, -88.038]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <group position={[-510.159, -17.934, -88.038]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.shaidao_55_10_D_qiang_5_0.geometry}
              material={materials.D_qiang_5}
              rotation={[-Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.shaidao_55_11_D_zhibei_12_0.geometry}
              material={materials.D_zhibei_12}
              position={[0, 8.818, 0]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.shaidao_55_12_D_zhibei_11_0.geometry}
              material={materials.D_zhibei_11}
              position={[0, 8.818, 0]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.shaidao_55_13_D_shui_1_0.geometry}
              material={materials.D_shui_1}
              position={[135.899, -17.063, 532]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.shaidao_55_3_D_tiezhalan_4_0.geometry}
              material={materials.D_tiezhalan_4}
              rotation={[-Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.shaidao_55_4_D_tiezhalan_1_0.geometry}
              material={materials.D_tiezhalan_1}
              rotation={[-Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.shaidao_55_5_D_qiang_2_0.geometry}
              material={materials.D_qiang_2}
              rotation={[-Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.shaidao_55_9_D_qiang_3_0.geometry}
              material={materials.D_qiang_3}
              rotation={[-Math.PI / 2, 0, 0]}
            />
          </group>
          <group position={[-510.159, -17.934, -88.038]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.shaidao_56_4_D_qiang_5_0.geometry}
              material={materials.D_qiang_5}
              rotation={[-Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.shaidao_56_5_D_qiang_3_0.geometry}
              material={materials.D_qiang_3}
              rotation={[-Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.shaidao_56_6_D_tiezhalan_1_0.geometry}
              material={materials.D_tiezhalan_1}
              rotation={[-Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.shaidao_56_7_D_qiang_2_0.geometry}
              material={materials.D_qiang_2}
              rotation={[-Math.PI / 2, 0, 0]}
            />
          </group>
          <group position={[-510.159, -17.934, -88.038]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.shaidao_57_3_D_tiezhalan_4_0.geometry}
              material={materials.D_tiezhalan_4}
              rotation={[-Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.shaidao_57_4_D_qiang_3_0.geometry}
              material={materials.D_qiang_3}
              rotation={[-Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.shaidao_57_6_D_zhibei_12_0.geometry}
              material={materials.D_zhibei_12}
              rotation={[-Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.shaidao_57_7_D_qiang_5_0.geometry}
              material={materials.D_qiang_5}
              rotation={[-Math.PI / 2, 0, 0]}
            />
          </group>
          <group position={[-510.159, -17.934, -88.038]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.shaidao_59_1_D_tiezhalan_1_0.geometry}
              material={materials.D_tiezhalan_1}
              rotation={[-Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.shaidao_59_3_D_qiang_2_0.geometry}
              material={materials.D_qiang_2}
              rotation={[-Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.shaidao_59_5_D_dibiao_8_0.geometry}
              material={materials.D_dibiao_8}
              rotation={[-Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.shaidao_59_6_D_tiezhalan_4_0.geometry}
              material={materials.D_tiezhalan_4}
              rotation={[-Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.shaidao_59_7_D_cao_3_0.geometry}
              material={materials.D_cao_3}
              rotation={[-Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.shaidao_59_8_D_dibiao_5_0.geometry}
              material={materials.D_dibiao_5}
              rotation={[-Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.shaidao_59_9_D_dibiao_9_0.geometry}
              material={materials.D_dibiao_9}
              rotation={[-Math.PI / 2, 0, 0]}
            />
          </group>
          <group position={[-510.159, -17.934, -88.038]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.shaidao_60_10_D_qiang_3_0.geometry}
              material={materials.D_qiang_3}
              rotation={[-Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.shaidao_60_11_D_qiang_5_0.geometry}
              material={materials.D_qiang_5}
              rotation={[-Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.shaidao_60_3_D_tiezhalan_4_0.geometry}
              material={materials.D_tiezhalan_4}
              rotation={[-Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.shaidao_60_5_D_qiang_2_0.geometry}
              material={materials.D_qiang_2}
              rotation={[-Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.shaidao_60_6_D_dibiao_5_0.geometry}
              material={materials.D_dibiao_5}
              rotation={[-Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.shaidao_60_7_D_qiang_5_0.geometry}
              material={materials.D_qiang_5}
              rotation={[-Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.shaidao_60_8_D_dibiao_13_0.geometry}
              material={materials.D_dibiao_13}
              rotation={[-Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.shaidao_60_9_D_cao_3_0.geometry}
              material={materials.D_cao_3}
              rotation={[-Math.PI / 2, 0, 0]}
            />
          </group>
          <group position={[-510.159, -17.934, -88.038]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.shaidao_61_2_D_tiezhalan_4_0.geometry}
              material={materials.D_tiezhalan_4}
              rotation={[-Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.shaidao_61_3_D_qiang_5_0.geometry}
              material={materials.D_qiang_5}
              rotation={[-Math.PI / 2, 0, 0]}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0.geometry}
            material={materials.D_hulang_1}
            position={[-301.333, -17.817, -189.615]}
            rotation={[-Math.PI / 2, 0, -2.327]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0001.geometry}
            material={materials.D_hulang_1}
            position={[-411.024, -17.8, -214.674]}
            rotation={[-Math.PI / 2, 0, -2.019]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0002.geometry}
            material={materials.D_hulang_1}
            position={[-1503.339, -20.627, -496.038]}
            rotation={[-Math.PI / 2, 0, 2.77]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0003.geometry}
            material={materials.D_hulang_1}
            position={[50.554, -17.796, 195.101]}
            rotation={[-Math.PI / 2, 0, -0.595]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0004.geometry}
            material={materials.D_hulang_1}
            position={[-929.092, -17.355, 137.179]}
            rotation={[-Math.PI / 2, 0, -1.614]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0005.geometry}
            material={materials.D_hulang_1}
            position={[-338.892, -17.817, -176.699]}
            rotation={[-Math.PI / 2, 0, -2.329]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0006.geometry}
            material={materials.D_hulang_1}
            position={[-1458.148, -17.774, -97.627]}
            rotation={[-Math.PI / 2, 0, 1.305]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0007.geometry}
            material={materials.D_hulang_1}
            position={[-149.053, -17.813, -79.579]}
            rotation={[-Math.PI / 2, 0, -2.991]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0008.geometry}
            material={materials.D_hulang_1}
            position={[-317.35, -17.817, -164.99]}
            rotation={[-Math.PI / 2, 0, -2.331]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0009.geometry}
            material={materials.D_hulang_1}
            position={[-1485.626, -17.864, 128.651]}
            rotation={[-Math.PI / 2, 0, 2.898]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0010.geometry}
            material={materials.D_hulang_1}
            position={[-151.49, -17.813, -85.51]}
            rotation={[-Math.PI / 2, 0, -2.991]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0011.geometry}
            material={materials.D_hulang_1}
            position={[75.127, -17.796, 220.616]}
            rotation={[-Math.PI / 2, 0, -0.61]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0012.geometry}
            material={materials.D_hulang_1}
            position={[-926.471, -17.355, 136.612]}
            rotation={[-Math.PI / 2, 0, -1.614]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0013.geometry}
            material={materials.D_hulang_1}
            position={[-819.205, -17.583, -478.867]}
            rotation={[-Math.PI / 2, 0, -2.053]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0014.geometry}
            material={materials.D_hulang_1}
            position={[81.556, -17.796, 202.532]}
            rotation={[-Math.PI / 2, 0, -0.61]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0015.geometry}
            material={materials.D_hulang_1}
            position={[-344.384, -17.817, -179.71]}
            rotation={[-Math.PI / 2, 0, -2.327]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0016.geometry}
            material={materials.D_hulang_1}
            position={[-902.302, -17.355, 132.898]}
            rotation={[-Math.PI / 2, 0, -1.773]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0017.geometry}
            material={materials.D_hulang_1}
            position={[-194.198, -17.813, -100.839]}
            rotation={[-Math.PI / 2, 0, -2.928]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0018.geometry}
            material={materials.D_hulang_1}
            position={[-357.999, -17.817, -187.014]}
            rotation={[-Math.PI / 2, 0, -2.323]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0019.geometry}
            material={materials.D_hulang_1}
            position={[-1470.215, -17.774, -97.627]}
            rotation={[-Math.PI / 2, 0, 1.305]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0020.geometry}
            material={materials.D_hulang_1}
            position={[-918.414, -17.355, 134.682]}
            rotation={[-Math.PI / 2, 0, -1.717]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0021.geometry}
            material={materials.D_hulang_1}
            position={[-328.418, -17.817, -170.971]}
            rotation={[-Math.PI / 2, 0, -2.312]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0022.geometry}
            material={materials.D_hulang_1}
            position={[-332.908, -17.817, -206.667]}
            rotation={[-Math.PI / 2, 0, -2.327]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0023.geometry}
            material={materials.D_hulang_1}
            position={[-391.922, -17.817, -237.976]}
            rotation={[-Math.PI / 2, 0, -2.278]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0024.geometry}
            material={materials.D_hulang_1}
            position={[-327.734, -17.817, -203.866]}
            rotation={[-Math.PI / 2, 0, -2.327]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0025.geometry}
            material={materials.D_hulang_1}
            position={[-389.549, -17.8, -236.871]}
            rotation={[-Math.PI / 2, 0, -2.318]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0026.geometry}
            material={materials.D_hulang_1}
            position={[-404.801, -17.8, -213.533]}
            rotation={[-Math.PI / 2, 0, -2.019]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0027.geometry}
            material={materials.D_hulang_1}
            position={[-1463.019, -17.774, -97.627]}
            rotation={[-Math.PI / 2, 0, 1.305]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0028.geometry}
            material={materials.D_hulang_1}
            position={[-309.651, -17.817, -160.745]}
            rotation={[-Math.PI / 2, 0, -2.312]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0029.geometry}
            material={materials.D_hulang_1}
            position={[-1485.626, -17.864, 132.799]}
            rotation={[-Math.PI / 2, 0, 2.898]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0030.geometry}
            material={materials.D_hulang_1}
            position={[-891.514, -17.311, 132.851]}
            rotation={[-Math.PI / 2, 0, -1.876]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0031.geometry}
            material={materials.D_hulang_1}
            position={[-335.524, -17.817, -208.068]}
            rotation={[-Math.PI / 2, 0, -2.327]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0032.geometry}
            material={materials.D_hulang_1}
            position={[-1455.9, -17.774, -97.627]}
            rotation={[-Math.PI / 2, 0, 1.305]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0033.geometry}
            material={materials.D_hulang_1}
            position={[-1479.744, -17.774, -97.629]}
            rotation={[-Math.PI / 2, 0, 1.305]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0034.geometry}
            material={materials.D_hulang_1}
            position={[-188.271, -17.813, -89.187]}
            rotation={[-Math.PI / 2, 0, -2.928]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0035.geometry}
            material={materials.D_hulang_1}
            position={[-337.954, -17.817, -209.397]}
            rotation={[-Math.PI / 2, 0, -2.327]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0036.geometry}
            material={materials.D_hulang_1}
            position={[-323.029, -17.817, -168.108]}
            rotation={[-Math.PI / 2, 0, -2.318]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0037.geometry}
            material={materials.D_hulang_1}
            position={[80.661, -17.796, 205.057]}
            rotation={[-Math.PI / 2, 0, -0.61]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0038.geometry}
            material={materials.D_hulang_1}
            position={[-1465.384, -17.774, -97.627]}
            rotation={[-Math.PI / 2, 0, 1.305]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0039.geometry}
            material={materials.D_hulang_1}
            position={[-401.781, -17.8, -212.996]}
            rotation={[-Math.PI / 2, 0, -2.019]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0040.geometry}
            material={materials.D_hulang_1}
            position={[-333.304, -17.817, -173.621]}
            rotation={[-Math.PI / 2, 0, -2.312]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0041.geometry}
            material={materials.D_hulang_1}
            position={[-355.149, -17.817, -185.492]}
            rotation={[-Math.PI / 2, 0, -2.325]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0042.geometry}
            material={materials.D_hulang_1}
            position={[51.659, -17.796, 192.187]}
            rotation={[-Math.PI / 2, 0, -0.61]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0043.geometry}
            material={materials.D_hulang_1}
            position={[79.677, -17.796, 208.009]}
            rotation={[-Math.PI / 2, 0, -0.61]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0044.geometry}
            material={materials.D_hulang_1}
            position={[-293.215, -17.817, -186.113]}
            rotation={[-Math.PI / 2, 0, -2.018]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0045.geometry}
            material={materials.D_hulang_1}
            position={[-481.12, -17.75, 231.644]}
            rotation={[-Math.PI / 2, 0, 0.869]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0046.geometry}
            material={materials.D_hulang_1}
            position={[-192.736, -17.813, -97.993]}
            rotation={[-Math.PI / 2, 0, -2.942]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0047.geometry}
            material={materials.D_hulang_1}
            position={[-349.759, -17.817, -182.571]}
            rotation={[-Math.PI / 2, 0, -2.306]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0048.geometry}
            material={materials.D_hulang_1}
            position={[-1485.626, -17.864, 144.628]}
            rotation={[-Math.PI / 2, 0, 2.898]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0049.geometry}
            material={materials.D_hulang_1}
            position={[-330.25, -17.817, -205.238]}
            rotation={[-Math.PI / 2, 0, -2.327]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0050.geometry}
            material={materials.D_hulang_1}
            position={[-899.749, -17.355, 132.709]}
            rotation={[-Math.PI / 2, 0, -1.773]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0051.geometry}
            material={materials.D_hulang_1}
            position={[73.946, -17.796, 223.638]}
            rotation={[-Math.PI / 2, 0, -0.61]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0052.geometry}
            material={materials.D_hulang_1}
            position={[-314.604, -17.817, -163.45]}
            rotation={[-Math.PI / 2, 0, -2.312]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0053.geometry}
            material={materials.D_hulang_1}
            position={[-394.6, -17.817, -239.281]}
            rotation={[-Math.PI / 2, 0, -2.278]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0054.geometry}
            material={materials.D_hulang_1}
            position={[-486.904, -17.719, 228.976]}
            rotation={[-Math.PI / 2, 0, 0.869]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0055.geometry}
            material={materials.D_hulang_1}
            position={[-894.247, -17.311, 132.828]}
            rotation={[-Math.PI / 2, 0, -1.876]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0056.geometry}
            material={materials.D_hulang_1}
            position={[-330.676, -17.817, -172.21]}
            rotation={[-Math.PI / 2, 0, -2.312]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0057.geometry}
            material={materials.D_hulang_1}
            position={[-341.729, -17.817, -178.278]}
            rotation={[-Math.PI / 2, 0, -2.318]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0058.geometry}
            material={materials.D_hulang_1}
            position={[-397.347, -17.817, -240.524]}
            rotation={[-Math.PI / 2, 0, -2.278]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0059.geometry}
            material={materials.D_hulang_1}
            position={[-361.19, -17.817, -189.767]}
            rotation={[-Math.PI / 2, 0, -2.693]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0060.geometry}
            material={materials.D_hulang_1}
            position={[-306.851, -17.817, -192.631]}
            rotation={[-Math.PI / 2, 0, -2.327]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0061.geometry}
            material={materials.D_hulang_1}
            position={[-191.07, -17.813, -94.788]}
            rotation={[-Math.PI / 2, 0, -2.942]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0062.geometry}
            material={materials.D_hulang_1}
            position={[-195.573, -17.813, -103.613]}
            rotation={[-Math.PI / 2, 0, -2.942]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0063.geometry}
            material={materials.D_hulang_1}
            position={[-320.001, -17.817, -199.678]}
            rotation={[-Math.PI / 2, 0, -2.327]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0064.geometry}
            material={materials.D_hulang_1}
            position={[-287.583, -17.817, -185.084]}
            rotation={[-Math.PI / 2, 0, -2.018]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0065.geometry}
            material={materials.D_hulang_1}
            position={[-888.955, -17.311, 132.924]}
            rotation={[-Math.PI / 2, 0, -1.876]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0066.geometry}
            material={materials.D_hulang_1}
            position={[-816.828, -17.583, -478.32]}
            rotation={[-Math.PI / 2, 0, -2.053]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0067.geometry}
            material={materials.D_hulang_1}
            position={[52.765, -17.796, 189.148]}
            rotation={[-Math.PI / 2, 0, -0.61]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0068.geometry}
            material={materials.D_hulang_1}
            position={[-1485.626, -17.864, 148.659]}
            rotation={[-Math.PI / 2, 0, 2.898]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0069.geometry}
            material={materials.D_hulang_1}
            position={[-1503.589, -20.627, -493.442]}
            rotation={[-Math.PI / 2, 0, 2.77]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0070.geometry}
            material={materials.D_hulang_1}
            position={[-365.119, -17.817, -194.23]}
            rotation={[-Math.PI / 2, 0, -2.695]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0071.geometry}
            material={materials.D_hulang_1}
            position={[-317.385, -17.817, -198.305]}
            rotation={[-Math.PI / 2, 0, -2.327]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0072.geometry}
            material={materials.D_hulang_1}
            position={[-907.701, -17.355, 133.3]}
            rotation={[-Math.PI / 2, 0, -1.773]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0073.geometry}
            material={materials.D_hulang_1}
            position={[77.385, -17.796, 214.295]}
            rotation={[-Math.PI / 2, 0, -0.61]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0074.geometry}
            material={materials.D_hulang_1}
            position={[-478.245, -17.775, 232.974]}
            rotation={[-Math.PI / 2, 0, 0.869]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0075.geometry}
            material={materials.D_hulang_1}
            position={[-152.621, -17.813, -88.273]}
            rotation={[-Math.PI / 2, 0, -2.991]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0076.geometry}
            material={materials.D_hulang_1}
            position={[-325.684, -17.817, -169.539]}
            rotation={[-Math.PI / 2, 0, -2.327]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0077.geometry}
            material={materials.D_hulang_1}
            position={[-1474.993, -17.774, -97.627]}
            rotation={[-Math.PI / 2, 0, 1.305]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0078.geometry}
            material={materials.D_hulang_1}
            position={[-325.232, -17.817, -202.494]}
            rotation={[-Math.PI / 2, 0, -2.327]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0079.geometry}
            material={materials.D_hulang_1}
            position={[-290.361, -17.817, -185.61]}
            rotation={[-Math.PI / 2, 0, -2.018]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0080.geometry}
            material={materials.D_hulang_1}
            position={[-483.996, -17.719, 230.332]}
            rotation={[-Math.PI / 2, 0, 0.869]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0081.geometry}
            material={materials.D_hulang_1}
            position={[-821.912, -17.583, -479.485]}
            rotation={[-Math.PI / 2, 0, -2.053]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0082.geometry}
            material={materials.D_hulang_1}
            position={[-296.073, -17.817, -186.913]}
            rotation={[-Math.PI / 2, 0, -2.206]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0083.geometry}
            material={materials.D_hulang_1}
            position={[-347.991, -17.817, -214.816]}
            rotation={[-Math.PI / 2, 0, -2.318]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0084.geometry}
            material={materials.D_hulang_1}
            position={[45.585, -17.796, 209.856]}
            rotation={[-Math.PI / 2, 0, -0.635]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0085.geometry}
            material={materials.D_hulang_1}
            position={[-340.484, -17.817, -210.755]}
            rotation={[-Math.PI / 2, 0, -2.327]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0086.geometry}
            material={materials.D_hulang_1}
            position={[-306.916, -17.817, -159.313]}
            rotation={[-Math.PI / 2, 0, -2.327]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0087.geometry}
            material={materials.D_hulang_1}
            position={[-475.207, -17.809, 234.34]}
            rotation={[-Math.PI / 2, 0, 0.869]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0088.geometry}
            material={materials.D_hulang_1}
            position={[-1472.588, -17.774, -97.627]}
            rotation={[-Math.PI / 2, 0, 1.305]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0089.geometry}
            material={materials.D_hulang_1}
            position={[-905.023, -17.355, 133.155]}
            rotation={[-Math.PI / 2, 0, -1.773]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0090.geometry}
            material={materials.D_hulang_1}
            position={[-304.192, -17.817, -191.13]}
            rotation={[-Math.PI / 2, 0, -2.327]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0091.geometry}
            material={materials.D_hulang_1}
            position={[-185.143, -17.813, -83.136]}
            rotation={[-Math.PI / 2, 0, -2.942]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0092.geometry}
            material={materials.D_hulang_1}
            position={[-352.918, -17.817, -217.485]}
            rotation={[-Math.PI / 2, 0, -2.327]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0093.geometry}
            material={materials.D_hulang_1}
            position={[-1641.172, -20.538, -541.418]}
            rotation={[-Math.PI / 2, 0, -1.895]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0094.geometry}
            material={materials.D_hulang_1}
            position={[44.697, -17.801, 212.232]}
            rotation={[-Math.PI / 2, 0, -0.65]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0095.geometry}
            material={materials.D_hulang_1}
            position={[-345.557, -17.817, -213.495]}
            rotation={[-Math.PI / 2, 0, -2.318]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0096.geometry}
            material={materials.D_hulang_1}
            position={[-1485.626, -17.864, 152.69]}
            rotation={[-Math.PI / 2, 0, 2.898]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0097.geometry}
            material={materials.D_hulang_1}
            position={[-489.66, -17.719, 227.734]}
            rotation={[-Math.PI / 2, 0, 0.869]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0098.geometry}
            material={materials.D_hulang_1}
            position={[-147.767, -17.813, -76.782]}
            rotation={[-Math.PI / 2, 0, -2.991]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0099.geometry}
            material={materials.D_hulang_1}
            position={[-347.119, -17.817, -181.142]}
            rotation={[-Math.PI / 2, 0, -2.312]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0100.geometry}
            material={materials.D_hulang_1}
            position={[48.449, -17.796, 201.166]}
            rotation={[-Math.PI / 2, 0, -0.595]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0101.geometry}
            material={materials.D_hulang_1}
            position={[-896.926, -17.311, 132.697]}
            rotation={[-Math.PI / 2, 0, -1.876]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0102.geometry}
            material={materials.D_hulang_1}
            position={[-320.192, -17.817, -166.529]}
            rotation={[-Math.PI / 2, 0, -2.329]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0103.geometry}
            material={materials.D_hulang_1}
            position={[-336.051, -17.817, -175.161]}
            rotation={[-Math.PI / 2, 0, -2.331]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0104.geometry}
            material={materials.D_hulang_1}
            position={[-1503.151, -20.627, -498.869]}
            rotation={[-Math.PI / 2, 0, 2.828]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0105.geometry}
            material={materials.D_hulang_1}
            position={[-314.855, -17.817, -196.948]}
            rotation={[-Math.PI / 2, 0, -2.327]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0106.geometry}
            material={materials.D_hulang_1}
            position={[-408.055, -17.8, -214.154]}
            rotation={[-Math.PI / 2, 0, -2.019]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0107.geometry}
            material={materials.D_hulang_1}
            position={[-311.976, -17.817, -162.04]}
            rotation={[-Math.PI / 2, 0, -2.312]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0108.geometry}
            material={materials.D_hulang_1}
            position={[-1477.423, -17.774, -97.627]}
            rotation={[-Math.PI / 2, 0, 1.305]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0109.geometry}
            material={materials.D_hulang_1}
            position={[-322.66, -17.817, -201.136]}
            rotation={[-Math.PI / 2, 0, -2.327]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0110.geometry}
            material={materials.D_hulang_1}
            position={[49.446, -17.796, 198.316]}
            rotation={[-Math.PI / 2, 0, -0.595]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0111.geometry}
            material={materials.D_hulang_1}
            position={[78.635, -17.796, 210.996]}
            rotation={[-Math.PI / 2, 0, -0.61]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0112.geometry}
            material={materials.D_hulang_1}
            position={[-1467.791, -17.774, -97.627]}
            rotation={[-Math.PI / 2, 0, 1.305]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0113.geometry}
            material={materials.D_hulang_1}
            position={[46.481, -17.796, 207.19]}
            rotation={[-Math.PI / 2, 0, -0.595]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0114.geometry}
            material={materials.D_hulang_1}
            position={[-1460.533, -17.774, -97.627]}
            rotation={[-Math.PI / 2, 0, 1.305]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0115.geometry}
            material={materials.D_hulang_1}
            position={[-1485.626, -17.864, 140.743]}
            rotation={[-Math.PI / 2, 0, 2.898]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0116.geometry}
            material={materials.D_hulang_1}
            position={[-363.144, -17.817, -192.162]}
            rotation={[-Math.PI / 2, 0, -2.657]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0117.geometry}
            material={materials.D_hulang_1}
            position={[-186.81, -17.813, -86.341]}
            rotation={[-Math.PI / 2, 0, -2.942]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0118.geometry}
            material={materials.D_hulang_1}
            position={[-189.647, -17.813, -91.961]}
            rotation={[-Math.PI / 2, 0, -2.942]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0119.geometry}
            material={materials.D_hulang_1}
            position={[-1643.968, -20.538, -541.603]}
            rotation={[-Math.PI / 2, 0, -1.895]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0120.geometry}
            material={materials.D_hulang_1}
            position={[-312.282, -17.817, -195.561]}
            rotation={[-Math.PI / 2, 0, -2.327]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0121.geometry}
            material={materials.D_hulang_1}
            position={[-1503.078, -20.627, -501.689]}
            rotation={[-Math.PI / 2, 0, 2.887]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0122.geometry}
            material={materials.D_hulang_1}
            position={[-921.334, -17.355, 135.336]}
            rotation={[-Math.PI / 2, 0, -1.614]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0123.geometry}
            material={materials.D_hulang_1}
            position={[-915.749, -17.355, 134.387]}
            rotation={[-Math.PI / 2, 0, -1.717]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0124.geometry}
            material={materials.D_hulang_1}
            position={[-923.825, -17.355, 135.927]}
            rotation={[-Math.PI / 2, 0, -1.614]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0125.geometry}
            material={materials.D_hulang_1}
            position={[-913.046, -17.355, 133.978]}
            rotation={[-Math.PI / 2, 0, -1.717]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0126.geometry}
            material={materials.D_hulang_1}
            position={[47.439, -17.796, 204.261]}
            rotation={[-Math.PI / 2, 0, -0.595]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0127.geometry}
            material={materials.D_hulang_1}
            position={[-150.279, -17.813, -82.603]}
            rotation={[-Math.PI / 2, 0, -2.991]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0128.geometry}
            material={materials.D_hulang_1}
            position={[54.014, -17.796, 186.372]}
            rotation={[-Math.PI / 2, 0, -0.692]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0129.geometry}
            material={materials.D_hulang_1}
            position={[-298.618, -17.817, -188.114]}
            rotation={[-Math.PI / 2, 0, -2.327]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0130.geometry}
            material={materials.D_hulang_1}
            position={[-350.445, -17.817, -216.154]}
            rotation={[-Math.PI / 2, 0, -2.332]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0131.geometry}
            material={materials.D_hulang_1}
            position={[76.273, -17.796, 217.456]}
            rotation={[-Math.PI / 2, 0, -0.61]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0132.geometry}
            material={materials.D_hulang_1}
            position={[-1485.626, -17.864, 136.742]}
            rotation={[-Math.PI / 2, 0, 2.898]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0133.geometry}
            material={materials.D_hulang_1}
            position={[-352.394, -17.817, -183.967]}
            rotation={[-Math.PI / 2, 0, -2.306]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0134.geometry}
            material={materials.D_hulang_1}
            position={[-301.424, -17.817, -156.303]}
            rotation={[-Math.PI / 2, 0, -2.329]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0135.geometry}
            material={materials.D_hulang_1}
            position={[-910.508, -17.355, 133.646]}
            rotation={[-Math.PI / 2, 0, -1.717]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0136.geometry}
            material={materials.D_hulang_1}
            position={[-343.101, -17.817, -212.143]}
            rotation={[-Math.PI / 2, 0, -2.327]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0137.geometry}
            material={materials.D_hulang_1}
            position={[-304.261, -17.817, -157.882]}
            rotation={[-Math.PI / 2, 0, -2.318]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hulang_2_D_hulang_1_0138.geometry}
            material={materials.D_hulang_1}
            position={[-309.524, -17.817, -194.075]}
            rotation={[-Math.PI / 2, 0, -2.327]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.luzhang_2_D_luzhang_2_0.geometry}
            material={materials.D_luzhang_2}
            position={[-1486.194, -18.186, 154.706]}
            rotation={[-Math.PI / 2, 0, 0.007]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.luzhang_2_D_luzhang_2_0001.geometry}
            material={materials.D_luzhang_2}
            position={[-499.226, -18.186, 226.603]}
            rotation={[-Math.PI / 2, 0, 2.726]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.luzhang_2_D_luzhang_2_0002.geometry}
            material={materials.D_luzhang_2}
            position={[-491.513, -18.186, 228.792]}
            rotation={[-Math.PI / 2, 0, 1.155]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.luzhang_2_D_luzhang_2_0003.geometry}
            material={materials.D_luzhang_2}
            position={[-1486.265, -18.186, 145.243]}
            rotation={[-Math.PI / 2, 0, 0.007]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.luzhang_2_D_luzhang_2_0004.geometry}
            material={materials.D_luzhang_2}
            position={[-502.845, -18.186, 234.805]}
            rotation={[-Math.PI / 2, 0, 2.726]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.luzhang_2_D_luzhang_2_0005.geometry}
            material={materials.D_luzhang_2}
            position={[-1469.797, -18.186, 155.07]}
            rotation={[-Math.PI / 2, 0, 1.583]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.luzhang_2_D_luzhang_2_0006.geometry}
            material={materials.D_luzhang_2}
            position={[-1478.094, -18.186, 155.162]}
            rotation={[-Math.PI / 2, 0, 1.583]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.luzhang_2_D_luzhang_2_0007.geometry}
            material={materials.D_luzhang_2}
            position={[-1453.132, -18.186, 154.886]}
            rotation={[-Math.PI / 2, 0, 1.583]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.luzhang_2_D_luzhang_2_0008.geometry}
            material={materials.D_luzhang_2}
            position={[-1461.429, -18.186, 154.977]}
            rotation={[-Math.PI / 2, 0, 1.583]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.luzhang_2_D_luzhang_2_0009.geometry}
            material={materials.D_luzhang_2}
            position={[-476.215, -18.186, 235.647]}
            rotation={[-Math.PI / 2, 0, 1.155]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.luzhang_2_D_luzhang_2_0010.geometry}
            material={materials.D_luzhang_2}
            position={[-1486.333, -18.186, 136.008]}
            rotation={[-Math.PI / 2, 0, 0.007]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.luzhang_2_D_luzhang_2_0011.geometry}
            material={materials.D_luzhang_2}
            position={[-483.827, -18.186, 232.184]}
            rotation={[-Math.PI / 2, 0, 1.155]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Scene_Paris_zhishi_D_jiantou_1_0.geometry}
            material={materials.D_jiantou_1}
            position={[-510.159, -17.934, -88.038]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.shaidao_54_1_D_dibiao_7_0.geometry}
          material={materials.D_dibiao_7}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.shaidao_54_2_D_lujian_4_0.geometry}
          material={materials.D_lujian_4}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.shaidao_55_1_D_dibiao_19_0.geometry}
          material={materials.D_dibiao_19}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.shaidao_55_2_D_lujian_4_0.geometry}
          material={materials.D_lujian_4}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.shaidao_55_7_D_dibiao_8_0.geometry}
          material={materials.D_dibiao_8}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.shaidao_56_1_D_dibiao_7_0.geometry}
          material={materials.D_dibiao_7}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.shaidao_56_2_D_lujian_4_0.geometry}
          material={materials.D_lujian_4}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.shaidao_56_3_D_dibiao_8_0.geometry}
          material={materials.D_dibiao_8}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.shaidao_57_1_D_dibiao_7_0.geometry}
          material={materials.D_dibiao_7}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.shaidao_57_2_D_lujian_4_0.geometry}
          material={materials.D_lujian_4}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.shaidao_57_5_D_dibiao_8_0.geometry}
          material={materials.D_dibiao_8}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.shaidao_59_2_D_dibiao_7_0.geometry}
          material={materials.D_dibiao_7}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.shaidao_59_4_D_lujian_4_0.geometry}
          material={materials.D_lujian_4}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.shaidao_60_1_D_dibiao_20_0.geometry}
          material={materials.D_dibiao_20}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.shaidao_60_2_D_lujian_4_0.geometry}
          material={materials.D_lujian_4}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.shaidao_60_4_D_dibiao_8_0.geometry}
          material={materials.D_dibiao_8}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.shaidao_61_1_D_dibiao_21_0.geometry}
          material={materials.D_dibiao_21}
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </group>
    </group>
  );
}
