import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import OggyHouse from "/ParisScene/OggyHouse.glb"

export default function Oggy(props) {
  const { nodes, materials } = useGLTF(OggyHouse)
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material2.geometry}
          material={materials.Fencing_Metal_Straight}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material2_1.geometry}
          material={materials.Ivory}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material4.geometry}
          material={materials.material_0}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3.geometry}
          material={materials.Water_Pool}
        />
        <lineSegments
          geometry={nodes.Material5.geometry}
          material={materials.edge_color255255240255}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material2_2.geometry}
          material={materials['0050_LemonChiffon']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3_1.geometry}
          material={materials.material}
        />
        <lineSegments
          geometry={nodes.Material6.geometry}
          material={materials.edge_color153153255255}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material4_1.geometry}
          material={materials.fish}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material2_3.geometry}
          material={materials.Color_H06}
        />
        <lineSegments
          geometry={nodes.Material3_2.geometry}
          material={materials.edge_color255250205255}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3_3.geometry}
          material={materials.Color_001}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3_4.geometry}
          material={materials.Beige_1}
        />
        <lineSegments
          geometry={nodes.Material5_1.geometry}
          material={materials.edge_color30153153255}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material2_4.geometry}
          material={materials.Color_H12}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material2_5.geometry}
          material={materials.LightGray}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3_5.geometry}
          material={materials.Color_I04}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material4_2.geometry}
          material={materials.walloggy}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material4_3.geometry}
          material={materials.Color_E07}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3_6.geometry}
          material={materials.phot}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3_7.geometry}
          material={materials.Wood_Floor_Light}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material2_6.geometry}
          material={materials.Color_E03}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material4_4.geometry}
          material={materials.material_23}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3_8.geometry}
          material={materials.Color_I03}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3_9.geometry}
          material={materials.Wood_Floor_Dark}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3_10.geometry}
          material={materials['0109_DarkSlateBlue']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3_11.geometry}
          material={materials.Tile_Checker_BW}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3_12.geometry}
          material={materials.Stone_Flagstone_Ashlar}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material2_7.geometry}
          material={materials.Translucent_Glass_Blue}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3_13.geometry}
          material={materials.Wood_Cherry_Original}
        />
        <lineSegments
          geometry={nodes.Material5_2.geometry}
          material={materials.edge_color1528642255}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3_14.geometry}
          material={materials.Metal_Rough}
        />
        <lineSegments
          geometry={nodes.Material4_5.geometry}
          material={materials.edge_color153157160255}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material2_8.geometry}
          material={materials.Color_000}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3_15.geometry}
          material={materials.Sketchy_Brick_Multi}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3_16.geometry}
          material={materials.Fencing_Weathered}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3_17.geometry}
          material={materials['sketch-stone']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3_18.geometry}
          material={materials.Groundcover_Sand_Raked}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3_19.geometry}
          material={materials.Vegetation_Bark_Maple}
        />
        <lineSegments
          geometry={nodes.Material3_20.geometry}
          material={materials.edge_color20400255}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material2_9.geometry}
          material={materials.Color_A06}
        />
        <lineSegments
          geometry={nodes.Material3_21.geometry}
          material={materials.edge_color169169169255}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material2_10.geometry}
          material={materials.Color_E12}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material2_11.geometry}
          material={materials.Color_C01}
        />
        <lineSegments
          geometry={nodes.Material3_22.geometry}
          material={materials.edge_color2551270255}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material2_12.geometry}
          material={materials.Color_J02}
        />
        <lineSegments
          geometry={nodes.Material4_6.geometry}
          material={materials.edge_color122122204255}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3_23.geometry}
          material={materials.Color_I09}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material2_13.geometry}
          material={materials['0135_DarkGray']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3_24.geometry}
          material={materials.WoodRough0023_2_thumbhuge}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3_25.geometry}
          material={materials.WoodPlanksBare0008_1_thumbhuge}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material2_14.geometry}
          material={materials.WoodRough0023_2_thumbhuge1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3_26.geometry}
          material={materials.jean_blue}
        />
        <lineSegments
          geometry={nodes.Material2_15.geometry}
          material={materials.edge_color000255}
        />
        <lineSegments
          geometry={nodes.Material3_27.geometry}
          material={materials.edge_color000255}
        />
        <lineSegments
          geometry={nodes.Material2_16.geometry}
          material={materials.edge_color0204204255}
        />
        <lineSegments
          geometry={nodes.Material2_17.geometry}
          material={materials.edge_color226226226255}
        />
        <lineSegments
          geometry={nodes.Material2_18.geometry}
          material={materials.edge_color7261139255}
        />
        <lineSegments
          geometry={nodes.Material4_7.geometry}
          material={materials.edge_color7261139255}
        />
        <lineSegments
          geometry={nodes.Material3_28.geometry}
          material={materials.edge_color12110285255}
        />
        <lineSegments
          geometry={nodes.Material2_19.geometry}
          material={materials.edge_color364766255}
        />
      </group>
    </group>
  )
}