/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Paul (https://sketchfab.com/paul_paul_paul)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/free-skybox-basic-sky-b2a4fd1b92c248abaae31975c9ea79e2
Title: FREE - SkyBox Basic Sky
*/

import { useGLTF } from "@react-three/drei";
import scene from "/free_-_skybox_basic_sky.glb";

export default function Sky(props) {
  const { nodes, materials } = useGLTF(scene);
  return (
    <group {...props} ref={props.innerRef} dispose={null} scale={20}>
      <group scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sphere__0.geometry}
          material={materials["Scene_-_Root"]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={2000}
        />
      </group>
    </group>
  );
}
