/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: toivo (https://sketchfab.com/toivo)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/car-scene-b7b32eaca80d460c9338197e2c9d1408
Title: Car Scene
*/

import carScene from "../assets/3d/car_scene.glb";
import { ObjectMap } from "@react-three/fiber";
import { useGLTF } from "@react-three/drei";

export default function VintageLantern(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(carScene) as ObjectMap;
  return (
    <group {...props} dispose={null} scale={0.02}>
      <group
        position={[54.766, -2.068, -284.313]}
        rotation={[-Math.PI / 2, 0, 0]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={
            (nodes.vintage_lantern_7_base_lantern_wall_base_2_0 as any).geometry
          }
          material={materials.lantern_wall_base_2}
        />
        <group position={[0.007, 0.078, 199.335]}>
          <mesh
            castShadow
            receiveShadow
            geometry={
              (nodes.vintage_lantern_glass_7_lantern_wall_glass_1_0 as any)
                .geometry
            }
            material={materials.lantern_wall_glass_1}
            position={[0.238, -7.28, 149.232]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              (nodes.vintage_lantern_7_lantern_wall_base_1_0 as any).geometry
            }
            material={materials.lantern_wall_base_1}
          />
        </group>
      </group>
    </group>
  );
}
