/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: toivo (https://sketchfab.com/toivo)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/car-scene-b7b32eaca80d460c9338197e2c9d1408
Title: Car Scene
*/

import { useGLTF } from "@react-three/drei";

export function WheelA(props) {
  const { nodes, materials } = useGLTF("/CarAndWheels/wheel.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.wheel_00_wheels_0.geometry}
        material={materials["wheels.002"]}
        position={[-71.898, 25.337, 62.764]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  );
}
