/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";

export function WheelA(props) {
  const { nodes, materials } = useGLTF("/CarAndWheels/wheel.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.wheel_00_wheels_0.geometry}
        material={materials["wheels.002"]}
        position={[-71.898, 25.337, 62.764]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  );
}
